'use strict';function z(g,a,b,d){g.s.Bb(g.bb,a,b,d,void 0)}function F(g,a,b,d){g.s.da?z(g,a,b,d):g.s.Bf()._OnMessageFromDOM({type:"event",component:g.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(g,a,b){g.s.C(g.bb,a,b)}function L(g,a){for(const [b,d]of a)J(g,b,d)}function N(g){g.Sb||(g.s.kf(g.re),g.Sb=!0)}window.pc=class{constructor(g,a){this.s=g;this.bb=a;this.Sb=!1;this.re=()=>this.Da()}nd(){}Da(){}};function O(g){-1!==g.Ra&&(self.clearTimeout(g.Ra),g.Ra=-1)}
window.$e=class{constructor(g,a){this.Uc=g;this.Vg=a;this.Ra=-1;this.Tb=-Infinity;this.se=()=>{this.Ra=-1;this.Tb=Date.now();this.hb=!0;this.Uc();this.hb=!1};this.Wd=this.hb=!1}f(){O(this);this.se=this.Uc=null}};"use strict";
function P(g,a){const b=a.elementId,d=g.rd(b,a);g.Y.set(b,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");a=g.Fc(d);a.addEventListener("focus",()=>{Q(g,"elem-focused",b)});a.addEventListener("blur",()=>{Q(g,"elem-blurred",b)});g.Ob&&document.body.appendChild(d)}function R(g,a){J(g,"get-element",b=>{const d=g.Y.get(b.elementId);return a(d,b)})}function Q(g,a,b){var d;d||(d={});d.elementId=b;z(g,a,d)}
window.Le=class extends self.pc{constructor(g,a){super(g,a);this.Y=new Map;this.Ob=!0;L(this,[["create",b=>P(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Ob&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Ob&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ob){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.Bc(d,b)}}],["focus",b=>{{const d=this.Fc(this.Y.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);R(this,b=>b)}rd(){throw Error("required override");}Bc(){throw Error("required override");}Fc(g){return g}};
"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.fh?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.kh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let f=!1,n=!1;function q(){if(!f){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}f=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function E(m){m=await x(m);return(new TextDecoder("utf-8")).decode(m)}
function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const G=[],A=new Map,H=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Db=class m{constructor(c){this.da=c.mh;this.ra=null;this.Z="";this.ic=c.jh;
this.xb={};this.Ka=this.wb=null;this.Qb=[];this.D=this.Pa=null;this.bd=!1;this.Zd=0;this.kb=null;this.Oa=-1;this.$g=()=>this.dg();this.Na=[];this.v=c.te;this.ib="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.da=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.da=!1;if("cordova"===this.v&&this.da)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.da=!1)}else this.da=!1;this.Wb=
this.ja=null;"html5"!==this.v&&"playable-ad"!==this.v||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",
k=>this.Jf(k));this.C("runtime","create-job-worker",()=>this.Kf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Hd(c)):this.Hd(c)}f(){this.Cc();this.ra&&(this.ra=this.ra.onmessage=null);this.wb&&(this.wb.terminate(),this.wb=null);this.Ka&&(this.Ka.f(),this.Ka=null);this.D&&(this.D.parentElement.removeChild(this.D),this.D=null)}Ve(){return g&&"cordova"===this.v}vc(){const c=navigator.userAgent;return g&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Te(){return a}vd(){return a&&
e.has(this.v)}async Hd(c){"macos-wkwebview"===this.v&&this.wg();if("playable-ad"===this.v){this.ja=self.c3_base64files;this.Wb={};await this.qf();for(let l=0,p=c.Sa.length;l<p;++l){var k=c.Sa[l].toLowerCase();this.Wb.hasOwnProperty(k)?c.Sa[l]={fh:!0,kh:this.Wb[k]}:this.ja.hasOwnProperty(k)&&(c.Sa[l]=URL.createObjectURL(this.ja[k]))}}c.ih?this.Z=c.ih:(k=location.origin,this.Z=("null"===k?"file:///":k)+location.pathname,k=this.Z.lastIndexOf("/"),-1!==k&&(this.Z=this.Z.substr(0,k+1)));c.oh&&(this.xb=
c.oh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Xf(l));this.kb=new self.We(this);await S(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((l,p)=>{window.AndroidFullScreen.immersiveMode(l,p)})}catch(l){console.error("Failed to enter Android immersive mode: ",l)}this.da?await this.Df(c,k.port2):
await this.Cf(c,k.port2)}Gc(c){c=this.xb.hasOwnProperty(c)?this.xb[c]:c.endsWith("/workermain.js")&&this.xb.hasOwnProperty("workermain.js")?this.xb["workermain.js"]:"playable-ad"===this.v&&this.ja.hasOwnProperty(c.toLowerCase())?this.ja[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async oc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.ib)return c=await this.yb(l.eh?c:this.ic+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),
l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Fd(c){var k=this.Z,l=location.href,p=this.pa(),u=this.ga(),r=window.devicePixelRatio,t=m.Va(),w=c.uh,D=window.cr_previewImageBlobs||this.ja,W=window.cr_previewProjectFileBlobs,X=window.cr_previewProjectFiles,Y=window.sh||
"";c=c.te;var Z=(new URLSearchParams(self.location.search)).has("debug"),M=this.kb;return{runtimeBaseUrl:k,previewUrl:l,windowInnerWidth:p,windowInnerHeight:u,devicePixelRatio:r,isFullscreen:t,projectData:w,previewImageBlobs:D,previewProjectFileBlobs:W,previewProjectFileSWUrls:X,swClientId:Y,exportType:c,isDebug:Z,ife:!!self.th,jobScheduler:{inputPort:M.ad,outputPort:M.gd,maxNumWorkers:M.Xg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ic+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.ic+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Ve(),isiOSWebView:this.vc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Df(c,k){var l=this.Gc(c.nh);this.wb=await this.oc(l,this.Z,{type:"module",name:"Runtime",eh:!0});this.D=document.createElement("canvas");this.D.style.display="none";l=this.D.transferControlToOffscreen();document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let p=c.md||[],u=c.Sa;
p=await Promise.all(p.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.v)for(let r=0,t=c.lc.length;r<t;++r){const w=c.lc[r],D=w[0];if(D===c.kd||"scriptsInEvents.js"===D||D.endsWith("/scriptsInEvents.js"))w[1]=await this.Ea(D)}this.wb.postMessage(Object.assign(this.Fd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.lc,mainProjectScript:c.kd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,
l,...aa(this.kb)]);this.Qb=G.map(r=>new r(this));this.Ed();self.c3_callFunction=(r,t)=>this.Pa.Ef(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.Bb("runtime","go-to-last-error-script"))}async Cf(c,k){this.D=document.createElement("canvas");this.D.style.display="none";document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Qb=G.map(r=>new r(this));this.Ed();var l=c.Sa.map(r=>"string"===typeof r?(new URL(r,this.Z)).toString():
r);Array.isArray(c.md)&&l.unshift(...c.md);l=await Promise.all(l.map(r=>this.Ea(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.kd,u=c.lc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ea(t),await d(t),"preview"!==this.v||l[r]||this.Qd(r,"main script did not run to completion")}catch(w){this.Qd(r,w)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await d(t);"preview"===this.v&&"object"!==typeof self.ph.qh?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Fd(c),{isInWorker:!1,messagePort:k,canvas:this.D,runOnStartupFunctions:K}),this.Jd(),this.Ka=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ka,c))}Qd(c,k){this.Lb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Jd(){this.Lb()}Lb(){const c=
window.ah;c&&(c.parentElement.removeChild(c),window.ah=null)}async Kf(){const c=await T(this.kb);return{outputPort:c,transferables:[c]}}Bf(){if(this.da)throw Error("not available in worker mode");return this.Ka}Bb(c,k,l,p,u){this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}xd(c,k,l,p,u){const r=I++,t=new Promise((w,D)=>{H.set(r,{resolve:w,reject:D})});this.ra.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Pf(c);if("result"===k)this.gg(c);else if("runtime-ready"===k)this.hg();else if("alert-error"===k)this.Lb(),alert(c.message);else if("creating-runtime"===k)this.Jd();else throw Error(`unknown message '${k}'`);}Pf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Kb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Kb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Kb(u,!1,""+t)}):this.Kb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Kb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.ra.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}gg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=H.get(k);l?p.resolve(c):p.reject(c);H.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static mc(c){if(G.includes(c))throw Error("DOM handler already added");G.push(c)}Ed(){for(const c of this.Qb)if("runtime"===c.bb){this.Pa=c;return}throw Error("cannot find runtime DOM handler");}Xf(c){this.Bb("debugger","message",c)}hg(){for(const c of this.Qb)c.nd()}static Va(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Rd(c){h=!!c}kf(c){this.Na.push(c);this.Rc()}tg(c){c=this.Na.indexOf(c);if(-1===c)throw Error("invalid callback");this.Na.splice(c,1);this.Na.length||this.Cc()}Rc(){-1===this.Oa&&this.Na.length&&(this.Oa=requestAnimationFrame(this.$g))}Cc(){-1!==this.Oa&&(cancelAnimationFrame(this.Oa),this.Oa=-1)}dg(){this.Oa=-1;for(const c of this.Na)c();this.Rc()}wa(c){this.Pa.wa(c)}Ca(c){this.Pa.Ca(c)}Qc(){this.Pa.Qc()}Fb(c){this.Pa.Fb(c)}Ue(){return!!B["audio/webm; codecs=opus"]}async Tg(c){c=await this.xd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}cf(c){this.bd=!0;this.Zd=c}Se(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}wd(c){return!this.Se(c)}async Ea(c){return"cordova"===this.v&&(c.startsWith("file:")||this.ib&&this.wd(c))?(c.startsWith(this.Z)&&(c=c.substr(this.Z.length)),c=await this.yb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Jf(c){const k=c.filename;switch(c.as){case "text":return await this.Ke(k);
case "buffer":return await this.yb(k);default:throw Error("unsupported type");}}qd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Ke(c){c=await this.qd(c);return await E(c)}Dc(){if(y.length&&!(8<=C)){C++;var c=y.shift();this.rf(c.filename,c.lh,c.dh)}}yb(c){return new Promise((k,l)=>{y.push({filename:c,lh:p=>{C--;this.Dc();k(p)},dh:p=>{C--;this.Dc();l(p)}});this.Dc()})}async rf(c,k,
l){try{const p=await this.qd(c),u=await x(p);k(u)}catch(p){l(p)}}wg(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async qf(){const c=[];for(const [k,l]of Object.entries(this.ja))c.push(this.pf(k,l));await Promise.all(c)}async pf(c,k){if("object"===typeof k)this.ja[c]=new Blob([k.str],
{type:k.type}),this.Wb[c]=k.str;else{let l=await this.zf(k);l||(l=this.tf(k));this.ja[c]=l}}async zf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}tf(c){c=this.ng(c);return this.nf(c.data,c.gh)}ng(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");
var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{gh:c,data:l}}nf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,w;for(w=t=0;t<p;++t)r[t]=c.charCodeAt(w++)|c.charCodeAt(w++)<<8|c.charCodeAt(w++)<<16|c.charCodeAt(w++)<<24;for(l&=3;l--;)u[w]=c.charCodeAt(w),++w;return new Blob([u],{type:k})}}}"use strict";
{const g=self.Db;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function E(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await E(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function A(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function H(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.mc(class extends self.pc{constructor(e){super(e,"runtime");this.ee=!0;this.Qa=-1;this.hd="any";this.Sd=this.Td=!1;this.ya=
null;this.W=!1;this.$d="";this.Xc=-1;this.Ja=this.sb=null;this.dc=this.cc=0;this.Yd=!1;this.ie=e.pa();this.Ub=e.ga();this.ub=0;e.C("canvas","update-size",c=>this.kg(c));e.C("runtime","invoke-download",c=>this.Vf(c));e.C("runtime","raster-svg-image",c=>this.eg(c));e.C("runtime","get-svg-image-size",c=>this.Tf(c));e.C("runtime","set-target-orientation",c=>this.ig(c));e.C("runtime","register-sw",()=>this.fg());e.C("runtime","post-to-debugger",c=>this.Md(c));e.C("runtime","go-to-script",c=>this.Md(c));
e.C("runtime","before-start-ticking",()=>this.If());e.C("runtime","debug-highlight",c=>this.Lf(c));e.C("runtime","enable-device-orientation",()=>this.mf());e.C("runtime","enable-device-motion",()=>this.lf());e.C("runtime","add-stylesheet",c=>this.Gf(c));e.C("runtime","alert",c=>this.Hf(c));e.C("runtime","hide-cordova-splash",()=>this.Uf());e.C("runtime","set-exporting-to-video",c=>this.Ag(c));e.C("runtime","export-to-video-progress",c=>this.Qf(c));e.C("runtime","exported-to-video",c=>this.Rf(c));
const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.D;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",
A)):m.addEventListener("touchstart",A);this.pb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",H,{passive:!1});window.addEventListener("wheel",H,{passive:!1});window.addEventListener("resize",()=>this.lg());window.addEventListener("fullscreenchange",()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",c=>
this.Mc(c));window.addEventListener("webkitfullscreenerror",c=>this.Mc(c));window.addEventListener("mozfullscreenerror",c=>this.Mc(c));if(e.vc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.mg(c);this.La=new Set;this.Yb=new WeakSet;this.qa=!1}If(){self.setTimeout(()=>{this.Yd=!0},1E3);"cordova"===this.s.v?(document.addEventListener("pause",()=>this.Pc(!0)),document.addEventListener("resume",()=>this.Pc(!1))):document.addEventListener("visibilitychange",()=>this.Pc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}nd(){window.addEventListener("focus",
()=>this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:K()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.Za("keyboard-blur")});window.addEventListener("keydown",h=>this.Kd("keydown",h));window.addEventListener("keyup",h=>this.Kd("keyup",h));window.addEventListener("dblclick",h=>this.Nc("dblclick",h,d));window.addEventListener("wheel",h=>this.Zf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Hc(h);this.Ya("pointerdown",h)}),this.s.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.$e(()=>this.wf(),5),this.sb.Wd=!0,window.addEventListener("pointerrawupdate",h=>this.cg(h))):window.addEventListener("pointermove",h=>this.Ya("pointermove",h)),window.addEventListener("pointerup",h=>this.Ya("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ya("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Hc(h);this.Oc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Oc("pointermove",h)),window.addEventListener("mouseup",h=>this.Oc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Hc(h);this.Jb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Jb("pointermove",h)),window.addEventListener("touchend",h=>this.Jb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Jb("pointercancel",h)));const e=()=>this.Qc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.s.Te()&&!this.s.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Kc(this.ga(),navigator.virtualKeyboard.boundingRect.height)}))}Kc(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/
2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}Za(e,h){z(this,e,h||null,n)}pa(){return this.s.pa()}ga(){return this.s.ga()}lg(){if(!this.W){var e=this.pa(),h=this.ga();if(this.s.vd()){if(this.Yd){if(this.ie===e&&h<this.Ub){this.ub=this.Ub-h;this.Kc(this.Ub,this.ub);return}0<this.ub&&(this.ub=0,this.Kc(h,this.ub))}this.ie=e;this.Ub=h}this.Za("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Va()});this.s.vc()&&
(-1!==this.Qa&&clearTimeout(this.Qa),this.Nd(e,h,0))}}ug(e,h,m){-1!==this.Qa&&clearTimeout(this.Qa);this.Qa=setTimeout(()=>this.Nd(e,h,m),48)}Nd(e,h,m){const c=this.pa(),k=this.ga();this.Qa=-1;c!=e||k!=h?this.Za("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Va()}):10>m&&this.ug(c,k,m+1)}ig(e){this.hd=e.targetOrientation}Pg(){const e=this.hd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",
h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Xa(){if(!this.W){var e=g.Va();e&&"any"!==this.hd&&this.Pg();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.pa(),
innerHeight:this.ga()})}}Mc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",{isFullscreen:g.Va(),innerWidth:this.pa(),innerHeight:this.ga()})}Pc(e){e?this.s.Cc():this.s.Rc();z(this,"visibilitychange",{hidden:e})}Kd(e,h){"Backspace"===h.key&&A(h);if(!this.W){var m=b.get(h.code)||h.code;F(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}}Zf(e){this.W||z(this,
"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Nc(e,h,m){this.W||a(h)||F(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Oc(e,h){if(!this.W&&!a(h)){var m=this.pb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");
F(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.pb=h.buttons;this.Nc(h.type,h,f)}}Ya(e,h){if(!this.W){if(this.sb&&"pointermove"!==e){var m=this.sb;m.hb||(O(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.pb);F(this,e,{pointerId:h.pointerId,
pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.cc,movementY:(h.movementY||0)+this.dc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.dc=this.cc=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),
this.Nc(m,h,f),this.pb=h.buttons)}}cg(e){this.Ja&&(this.cc+=this.Ja.movementX||0,this.dc+=this.Ja.movementY||0);this.Ja=e;e=this.sb;if(-1===e.Ra){var h=Date.now(),m=h-e.Tb,c=e.Vg;m>=c&&e.Wd?(e.Tb=h,e.hb=!0,e.Uc(),e.hb=!1):e.Ra=self.setTimeout(e.se,Math.max(c-m,4))}}wf(){this.Ya("pointermove",this.Ja);this.Ja=null}Jb(e,h){if(!this.W)for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];F(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,
clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Hc(e){window!==window.top&&window.focus();this.Id(e.target)&&document.activeElement&&!this.Id(document.activeElement)&&document.activeElement.blur()}Id(e){return!e||e===document||e===window||e===document.body||
"canvas"===e.tagName.toLowerCase()}mf(){this.Td||(this.Td=!0,window.addEventListener("deviceorientation",e=>this.Nf(e)),window.addEventListener("deviceorientationabsolute",e=>this.Of(e)))}lf(){this.Sd||(this.Sd=!0,window.addEventListener("devicemotion",e=>this.Mf(e)))}Nf(e){this.W||z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Of(e){this.W||
z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Mf(e){if(!this.W){var h=null,m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}}kg(e){var h=this.s;h.bd||(h=h.D,h.style.width=e.styleWidth+"px",h.style.height=e.styleHeight+"px",h.style.marginLeft=e.marginLeft+"px",h.style.marginTop=e.marginTop+"px",this.ee&&(h.style.display="",this.ee=!1))}Vf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async eg(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,
e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Tf(e){return await self.C3_GetSvgImageSize(e.blob)}async Gf(e){await q(e.url)}Qc(){var e=[...this.La];this.La.clear();if(!this.qa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Yb.has(h)||this.La.add(h)})}wa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Yb.delete(e);let h;try{h=e.play()}catch(m){this.La.add(e);return}h&&h.catch(()=>{this.Yb.has(e)||
this.La.add(e)})}Ca(e){this.La.delete(e);this.Yb.add(e)}Fb(e){this.qa=!!e}Uf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Lf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}fg(){window.C3_RegisterSW&&
window.C3_RegisterSW()}Md(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Ef(e,h){return this.s.xd(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Hf(e){alert(e.message)}mg(e){"entered-fullscreen"===e?(g.Rd(!0),this.Xa()):"exited-fullscreen"===e?(g.Rd(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}Ag(e){this.W=!0;const h=document.createElement("h1");h.id="exportToVideoMessage";h.textContent=e.message;document.body.prepend(h);document.body.classList.add("exportingToVideo");
this.s.D.style.display="";this.s.cf(e.duration)}Qf(e){this.$d=e.message;-1===this.Xc&&(this.Xc=setTimeout(()=>this.xf(),250))}xf(){this.Xc=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.$d)}Rf(e){window.rh({type:"exported-video",blob:e.blob,time:e.time})}})}"use strict";
async function S(g){if(g.Ug)throw Error("already initialised");g.Ug=!0;var a=g.hc.Gc("dispatchworker.js");g.Wc=await g.hc.oc(a,g.ab,{name:"DispatchWorker"});a=new MessageChannel;g.ad=a.port1;g.Wc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.gd=await T(g)}function aa(g){return[g.ad,g.gd]}
async function T(g){const a=g.fe.length;var b=g.hc.Gc("jobworker.js");b=await g.hc.oc(b,g.ab,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Wc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.fe.push(b);return f.port1}
self.We=class{constructor(g){this.hc=g;this.ab=g.Z;this.ab="preview"===g.v?this.ab+"workers/":this.ab+g.ic;this.Xg=Math.min(navigator.hardwareConcurrency||2,16);this.Wc=null;this.fe=[];this.gd=this.ad=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Db({mh:!0,nh:"workermain.js",Sa:["scripts/c3runtime.js"],lc:[],kd:"",jh:"scripts/",md:[],te:"html5"}));"use strict";
{function g(a){a.stopPropagation()}self.Db.mc(class extends self.Le{constructor(a){super(a,"button")}rd(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("pointerdown",
g);f.addEventListener("pointermove",g);f.addEventListener("pointerrawupdate",g);f.addEventListener("pointerup",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>{var n={isChecked:d.checked};n.elementId=a;F(this,"click",n)});b.id&&(d.id=b.id);b.className&&(d.className=b.className);this.Bc(f,b);return f}Gd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Fc(a){return this.Gd(a)}Bc(a,
b){const d=this.Gd(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.ea=class extends self.pc{constructor(a){super(a,"audio");this.Ha=this.a=null;this.Rb=this.$c=!1;this.ta=()=>this.Qg();this.ba=[];this.J=[];this.ia=null;this.ge="";this.he=-1;this.rb=new Map;this.Xb=1;this.qa=!1;this.jd=0;this.jc=1;this.Yc=0;this.ke="HRTF";this.Xd="inverse";this.le=600;this.je=1E4;this.ne=1;this.be=this.ac=!1;this.qe=this.s.Ue();this.ca=new Map;this.Ga=new Set;this.ce=this.cd=!1;this.ed="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Yf(b,d);this.Pb=
null;self.C3Audio_GetOutputStream=()=>this.Sf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.sf(b)],["play",b=>this.og(b)],["stop",b=>this.Ng(b)],["stop-all",()=>this.Og()],["set-paused",b=>this.Gg(b)],["set-volume",b=>this.Lg(b)],["fade-volume",b=>this.yf(b)],["set-master-volume",b=>this.Eg(b)],["set-muted",b=>this.Fg(b)],["set-silent",b=>this.Ig(b)],["set-looping",b=>this.Dg(b)],["set-playback-rate",b=>this.Hg(b)],["seek",b=>this.vg(b)],["preload",b=>this.pg(b)],["unload",
b=>this.Rg(b)],["unload-all",()=>this.Sg()],["set-suspended",b=>this.Jg(b)],["add-effect",b=>this.Cd(b)],["set-effect-param",b=>this.zg(b)],["remove-effects",b=>this.rg(b)],["tick",b=>this.jg(b)],["load-state",b=>this.Wf(b)],["offline-render-audio",b=>this.$f(b)],["offline-render-finish",()=>this.bg()]])}async sf(a){a.isiOSCordova&&(this.ac=!0);this.jd=a.timeScaleMode;this.ke=["equalpower","HRTF","soundfield"][a.panningModel];this.Xd=["linear","inverse","exponential"][a.distanceModel];this.le=a.refDistance;
this.je=a.maxDistance;this.ne=a.rolloffFactor;if(this.s.bd)this.ac=!0,this.a=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*this.s.Zd)});else{var b={latencyHint:a.latencyHint};this.qe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.a=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.a=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Dd();this.a.onstatechange=()=>{"running"!==this.a.state&&this.Dd();
z(this,"audiocontext-state",{audioContextState:this.a.state})}}this.Ha=this.a.createGain();this.Ha.connect(this.a.destination);b=a.listenerPos;this.a.listener.setPosition(b[0],b[1],b[2]);this.a.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.qc();try{await Promise.all(a.preloadList.map(d=>this.Hb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.a.sampleRate,audioContextState:this.a.state}}Dd(){this.Rb||
(this.$c=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Rb=!0)}uf(){this.Rb&&(this.$c=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Rb=!1)}Qg(){if(!this.$c){var a=this.a;"suspended"===a.state&&a.resume&&
a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.uf()}}V(){return this.a}qc(){return this.a.currentTime}ua(){return this.Ha}td(a){return(a=this.ca.get(a.toLowerCase()))?a[0].O():this.ua()}ue(a,b){a=a.toLowerCase();let d=this.ca.get(a);d||(d=[],this.ca.set(a,d));b.Cg(d.length);b.Kg(a);d.push(b);this.Pd(a)}Pd(a){let b=this.ua();const d=this.ca.get(a);if(d&&d.length){b=d[0].O();for(let f=0,n=d.length;f<n;++f){const q=
d[f];f+1===n?q.R(this.ua()):q.R(d[f+1].O())}}for(const f of this.na(a))f.af(b);this.za&&this.ed===a&&(this.za.disconnect(),this.za.connect(b))}Ab(){return this.qa}Bg(){this.be=!0}Ne(a,b){return b?this.s.Tg(a).then(d=>{const f=this.a.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):new Promise((d,f)=>{this.a.decodeAudioData(a,d,f)})}wa(a){this.s.wa(a)}Ca(a){this.s.Ca(a)}yd(a){let b=0;for(let d=0,f=this.J.length;d<f;++d){const n=this.J[d];this.J[b]=n;n.K===a?n.f():++b}this.J.length=
b}bf(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const f=this.ba[b];this.ba[a]=f;f.va()?f.f():++a}this.ba.length=a}*na(a){if(a)for(const b of this.J)self.ea.Oe(b.$,a)&&(yield b);else this.ia&&!this.ia.S()&&(yield this.ia)}async Hb(a,b,d,f,n){for(const q of this.ba)if(q.Ua()===b)return await U(q),q;if(n)return null;f&&(this.ac||this.be)&&this.bf();n="audio/webm; codecs=opus"===d&&!this.qe;f&&n&&this.Bg();a=!f||this.ac||n?new self.Ie(this,a,b,d,f,n):new self.Ge(this,a,b,d,f);this.ba.push(a);await U(a);
return a}async Ec(a,b,d,f,n){for(const q of this.J)if(q.Ua()===b&&(q.nc()||n))return q.ef(f),q;a=await this.Hb(a,b,d,n);f="html5"===a.Tc?new self.He(a.j,a,f):new self.Je(a.j,a,f);this.J.push(f);return f}jf(a){let b=this.rb.get(a);if(!b){let d=null;b={ld:0,hh:new Promise(f=>d=f),resolve:d};this.rb.set(a,b)}b.ld++}sg(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.ld--;0===b.ld&&(b.resolve(),this.rb.delete(a))}Ac(a){a||(a=this.ge);return(a=this.rb.get(a))?a.hh:Promise.resolve()}Ib(){if(0<
this.Ga.size)N(this);else for(const a of this.J)if(a.ud()){N(this);break}}Da(){for(var a of this.Ga)a.Da();a=this.qc();for(var b of this.J)b.Da(a);b=this.J.filter(d=>d.ud()).map(d=>d.Ta());z(this,"state",{tickCount:this.he,audioInstances:b,analysers:[...this.Ga].map(d=>d.Qe())});0===b.length&&0===this.Ga.size&&this.Sb&&(this.s.tg(this.re),this.Sb=!1)}wc(a,b,d){z(this,"trigger",{type:a,tag:b,aiid:d})}async og(a){const b=a.originalUrl,d=a.url,f=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,E=a.pos,
x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.a.getOutputTimestamp?(a=this.a.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.a.currentTime);this.ge=q;this.jf(q);try{this.ia=await this.Ec(b,d,f,q,n),x?(this.ia.Eb(!0),this.ia.df(x.x,x.y,x.angle,x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ia.ff(x.uid)):this.ia.Eb(!1),this.ia.Play(v,B,E,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.sg(q)}N(this)}Ng(a){a=
a.tag;for(const b of this.na(a))b.oa()}Og(){for(const a of this.J)a.oa()}Gg(a){const b=a.tag;a=a.paused;for(const d of this.na(b))a?d.Wa():d.Cb();this.Ib()}Lg(a){const b=a.tag;a=a.vol;for(const d of this.na(b))d.Gb(a)}async yf(a){const b=a.tag,d=a.vol,f=a.duration;a=a.stopOnEnd;await this.Ac(b);for(const n of this.na(b))n.Pe(d,f,a);this.Ib()}Eg(a){this.Xb=a.vol;this.Ha.gain.value=this.Xb}Fg(a){const b=a.tag;a=a.isMuted;for(const d of this.na(b))d.zd(a)}Ig(a){this.qa=a.isSilent;this.s.Fb(this.qa);
for(const b of this.J)b.Mb()}Dg(a){const b=a.tag;a=a.isLooping;for(const d of this.na(b))d.yc(a)}async Hg(a){const b=a.tag;a=a.rate;await this.Ac(b);for(const d of this.na(b))d.Bd(a)}async vg(a){const b=a.tag;a=a.pos;await this.Ac(b);for(const d of this.na(b))d.xc(a)}async pg(a){const b=a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.Ec(b,d,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Rg(a){if(a=await this.Hb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.ba.indexOf(a),
-1!==a&&this.ba.splice(a,1)}Sg(){for(const a of this.ba)a.f();this.ba.length=0}Jg(a){a=a.isSuspended;!a&&this.a.resume&&this.a.resume();for(const b of this.J)b.zc(a);a&&this.a.suspend&&this.a.suspend()}jg(a){this.jc=a.timeScale;this.Yc=a.gameTime;this.he=a.tickCount;if(0!==this.jd)for(var b of this.J)b.Fa();(b=a.listenerPos)&&this.a.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.J)f.ha===a&&f.Ad(d.x,d.y,d.angle)}}async Cd(a){var b=a.type;const d=a.tag;
var f=a.params;if("filter"===b)f=new self.Ae(this,...f);else if("delay"===b)f=new self.ye(this,...f);else if("convolution"===b){b=null;try{b=await this.Hb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}f=new self.xe(this,b.aa,...f);f.xg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.Be(this,...f);else if("phaser"===b)f=new self.De(this,...f);else if("gain"===b)f=new self.Ce(this,...f);else if("tremolo"===
b)f=new self.Fe(this,...f);else if("ringmod"===b)f=new self.Ee(this,...f);else if("distortion"===b)f=new self.ze(this,...f);else if("compressor"===b)f=new self.we(this,...f);else if("analyser"===b)f=new self.ve(this,...f);else throw Error("invalid effect type");this.ue(d,f);this.Od()}zg(a){const b=a.index,d=a.param,f=a.value,n=a.ramp,q=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,n,q),this.Od())}rg(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.f();
this.ca.delete(a);this.Pd(a)}}hf(a){this.Ga.add(a);this.Ib()}qg(a){this.Ga.delete(a)}Od(){this.cd||(this.cd=!0,Promise.resolve().then(()=>this.vf()))}vf(){const a={};for(const [b,d]of this.ca)a[b]=d.map(f=>f.Ta());z(this,"fxstate",{fxstate:a});this.cd=!1}async Wf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.J)d.va()&&1===b||(d.va()||2!==b)&&d.oa();for(const f of this.ca.values())for(const n of f)n.f();this.ca.clear();this.jc=a.timeScale;this.Yc=a.gameTime;d=a.listenerPos;this.a.listener.setPosition(d[0],
d[1],d[2]);this.qa=a.isSilent;this.s.Fb(this.qa);this.Xb=a.masterVolume;this.Ha.gain.value=this.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(n=>this.Cd(n))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.Ff(f,b)));this.Ib()}async Ff(a,b){if(3!==b){var d=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,E=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Ec(d,f,n,v,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",
y);return}b.Ze(a.pan);b.Play(B,E,x,0);a.isPlaying||b.Wa();b.Jc(a)}}}Yf(a,b){this.za&&this.za.disconnect();this.ed=b.toLowerCase();this.za=this.a.createMediaStreamSource(a);this.za.connect(this.td(this.ed))}Sf(){this.Pb||(this.Pb=this.a.createMediaStreamDestination(),this.Ha.connect(this.Pb));return this.Pb.stream}async $f(a){try{const b=this.a.suspend(a.time);this.ce?this.a.resume():(this.a.startRendering().then(d=>this.ag(d)).catch(d=>this.Ld(d)),this.ce=!0);await b}catch(b){this.Ld(b)}}bg(){this.a.resume()}ag(a){const b=
[];for(let d=0,f=a.numberOfChannels;d<f;++d){const n=a.getChannelData(d);b.push(n.buffer)}this.s.Bb("runtime","offline-audio-render-completed",{duration:a.duration,length:a.length,numberOfChannels:a.numberOfChannels,sampleRate:a.sampleRate,channelData:b},null,b)}Ld(a){console.error("[Audio] Offline rendering error: ",a)}static Oe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static gf(a){return a*g}static Me(a){return Math.pow(10,a/20)}static sd(a){return Math.max(Math.min(self.ea.Me(a),
1),0)}static Ye(a){return Math.log(a)/Math.log(10)*20}static Xe(a){return self.ea.Ye(Math.max(Math.min(a,1),0))}static bh(a,b){return 1-Math.exp(-b*a)}};self.Db.mc(self.ea)}"use strict";function U(g){g.Vb||(g.Vb=g.Ic());return g.Vb}self.od=class{constructor(g,a,b,d,f){this.j=g;this.Zg=a;this.Aa=b;this.P=d;this.Wg=f;this.Tc="";this.Vb=null}f(){this.Vb=this.j=null}Ic(){}V(){return this.j.V()}sc(){return this.Zg}Ua(){return this.Aa}rc(){return this.P}va(){return this.Wg}fa(){}};"use strict";
self.Ge=class extends self.od{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Tc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.lb=this.mb=null;this.I.addEventListener("canplaythrough",()=>!0);this.qb=this.V().createGain();this.ob=null;this.I.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.I&&(this.ob=this.V().createMediaElementSource(this.I),this.ob.connect(this.qb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,n);this.lb&&(this.lb(n),this.lb=this.mb=null)})}f(){this.j.yd(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.f()}Ic(){return new Promise((g,a)=>{this.mb=g;this.lb=a;this.I.src=this.Aa})}N(){return this.I}fa(){return this.I.duration}};"use strict";
async function ba(g){if(g.xa)return g.xa;var a=g.j.s;if("cordova"===a.v&&a.wd(g.Aa)&&a.ib)g.xa=await a.yb(g.Aa);else{a=await fetch(g.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.xa=await a.arrayBuffer()}}async function ca(g){if(g.aa)return g.aa;g.aa=await g.j.Ne(g.xa,g.Yg);g.xa=null}
self.Ie=class extends self.od{constructor(g,a,b,d,f,n){super(g,a,b,d,f);this.Tc="webaudio";this.aa=this.xa=null;this.Yg=!!n}f(){this.j.yd(this);this.aa=this.xa=null;super.f()}async Ic(){try{await ba(this),await ca(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,g)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let g=0;self.pd=class{constructor(a,b,d){this.j=a;this.K=b;this.$=d;this.Nb=g++;this.L=this.V().createGain();this.L.connect(this.ua());this.B=null;this.jb=!1;this.la=[0,0,0];this.ka=[0,0,0];this.G=!0;this.U=this.ma=this.F=!1;this.vb=1;this.Ia=!1;this.sa=1;a=this.j.jd;this.dd=1===a&&!this.va()||2===a;this.fb=this.ha=-1;this.pe=!1}f(){this.K=this.j=null;this.B&&(this.B.disconnect(),this.B=null);this.L.disconnect();this.L=null}V(){return this.j.V()}ua(){return this.j.td(this.$)}zb(){return this.dd?
this.j.Yc:performance.now()/1E3}sc(){return this.K.sc()}Ua(){return this.K.Ua()}rc(){return this.K.rc()}va(){return this.K.va()}ef(a){this.$=a}S(){}nc(){}IsPlaying(){return!this.G&&!this.F&&!this.S()}ud(){return!this.G&&!this.S()}Ba(){}fa(){return this.K.fa()}Play(){}oa(){}Wa(){}Cb(){}Gb(a){this.vb=a;this.L.gain.cancelScheduledValues(0);this.fb=-1;this.L.gain.value=this.tc()}Pe(a,b,d){if(!this.Ia){var f=this.L.gain;f.cancelScheduledValues(0);var n=this.j.qc();b=n+b;f.setValueAtTime(f.value,n);f.linearRampToValueAtTime(a,
b);this.vb=a;this.fb=b;this.pe=d}}Sc(){this.Gb(this.vb)}Da(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.pe&&this.oa(),this.j.wc("fade-ended",this.$,this.Nb))}tc(){const a=this.vb;return isFinite(a)?a:0}zd(a){a=!!a;this.Ia!==a&&(this.Ia=a,this.Mb())}Ab(){return this.j.Ab()}Mb(){}yc(){}Bd(a){this.sa!==a&&(this.sa=a,this.Fa())}Fa(){}xc(){}zc(){}Eb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.V().createPanner(),this.B.panningModel=this.j.ke,this.B.distanceModel=this.j.Xd,this.B.refDistance=
this.j.le,this.B.maxDistance=this.j.je,this.B.rolloffFactor=this.j.ne),this.L.disconnect(),this.L.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.L.disconnect(),this.L.connect(this.ua())))}df(a,b,d,f,n,q){this.jb&&(this.Ad(a,b,d),a=self.ea.gf,this.B.coneInnerAngle=a(f),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Ad(a,b,d){this.jb&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(d),this.ka[1]=Math.sin(d),this.ka[2]=0,this.B.setPosition(...this.la),this.B.setOrientation(...this.ka))}ff(a){this.ha=
a}uc(){}af(a){const b=this.B||this.L;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Nb,tag:this.$,duration:this.fa(),volume:this.vb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.va(),isLooping:this.U,isMuted:this.Ia,resumePosition:this.uc(),pan:this.Re()}}Jc(a){this.Bd(a.playbackRate);this.zd(a.isMuted)}Re(){if(!this.B)return null;const a=this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,
coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Ze(a){if(a){this.Eb(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Eb(!1)}}}"use strict";
self.He=class extends self.pd{constructor(g,a,b){super(g,a,b);this.K.qb.connect(this.L);this.K.onended=()=>this.Lc()}f(){this.oa();this.K.qb.disconnect();super.f()}N(){return this.K.N()}Lc(){this.G=!0;this.ha=-1;this.j.wc("ended",this.$,this.Nb)}S(){return this.N().ended}nc(){return this.G?!0:this.S()}Ba(){let g=this.N().currentTime;this.U||(g=Math.min(g,this.fa()));return g}Play(g,a,b){const d=this.N();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Gb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.K.Ua()}' to position '${b}': `,f)}this.j.wa(d);this.F=this.G=!1;this.U=g;this.sa=1}oa(){const g=this.N();g.paused||g.pause();this.j.Ca(g);this.G=!0;this.F=!1;this.ha=-1}Wa(){if(!(this.F||this.G||this.S())){var g=this.N();g.paused||g.pause();this.j.Ca(g);this.F=!0}}Cb(){!this.F||this.G||this.S()||(this.j.wa(this.N()),this.F=!1)}Mb(){this.N().muted=this.Ia||this.Ab()}yc(g){g=!!g;this.U!==g&&
(this.U=g,this.N().loop=g)}Fa(){let g=this.sa;this.dd&&(g*=this.j.jc);try{this.N().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}xc(g){if(!this.G&&!this.S())try{this.N().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}uc(){return this.Ba()}zc(g){g?this.IsPlaying()?(this.N().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.j.wa(this.N()),this.ma=!1)}};"use strict";
function V(g){g.i&&g.i.disconnect();g.i=null;g.$a=null}
self.Je=class extends self.pd{constructor(g,a,b){super(g,a,b);this.i=null;this.Zb=d=>this.Lc(d);this.Zc=!0;this.$a=null;this.M=this.$b=this.bc=0;this.fd=1}f(){this.oa();V(this);this.Zb=null;super.f()}Lc(g){this.F||this.ma||g.target!==this.$a||(this.G=this.Zc=!0,this.ha=-1,V(this),this.j.wc("ended",this.$,this.Nb))}S(){return!this.G&&this.i&&this.i.loop||this.F?!1:this.Zc}nc(){return!this.i||this.G?!0:this.S()}Ba(){let g;g=this.F?this.M:this.$b+(this.zb()-this.bc)*this.sa;this.U||(g=Math.min(g,this.fa()));
return g}Play(g,a,b,d){this.fd=1;this.Gb(a);V(this);this.i=this.V().createBufferSource();this.i.buffer=this.K.aa;this.i.connect(this.L);this.$a=this.i;this.i.onended=this.Zb;this.i.loop=g;this.i.start(d,b);this.F=this.G=this.Zc=!1;this.U=g;this.sa=1;this.bc=this.zb();this.$b=b}oa(){if(this.i)try{this.i.stop(0)}catch(g){}this.G=!0;this.F=!1;this.ha=-1}Wa(){this.F||this.G||this.S()||(this.M=this.Ba(),this.U&&(this.M%=this.fa()),this.F=!0,this.i.stop(0))}Cb(){!this.F||this.G||this.S()||(V(this),this.i=
this.V().createBufferSource(),this.i.buffer=this.K.aa,this.i.connect(this.L),this.$a=this.i,this.i.onended=this.Zb,this.i.loop=this.U,this.Sc(),this.Fa(),this.i.start(0,this.M),this.bc=this.zb(),this.$b=this.M,this.F=!1)}tc(){return super.tc()*this.fd}Mb(){this.fd=this.Ia||this.Ab()?0:1;this.Sc()}yc(g){g=!!g;this.U!==g&&(this.U=g,this.i&&(this.i.loop=g))}Fa(){let g=this.sa;this.dd&&(g*=this.j.jc);this.i&&(this.i.playbackRate.value=g)}xc(g){this.G||this.S()||(this.F?this.M=g:(this.Wa(),this.M=g,this.Cb()))}uc(){return this.M}zc(g){g?
this.IsPlaying()?(this.ma=!0,this.M=this.Ba(),this.U&&(this.M%=this.fa()),this.i.stop(0)):this.ma=!1:this.ma&&(V(this),this.i=this.V().createBufferSource(),this.i.buffer=this.K.aa,this.i.connect(this.L),this.$a=this.i,this.i.onended=this.Zb,this.i.loop=this.U,this.Sc(),this.Fa(),this.i.start(0,this.M),this.bc=this.zb(),this.$b=this.M,this.ma=!1)}Jc(g){super.Jc(g);this.M=g.resumePosition}};"use strict";
{class g{constructor(a){this.j=a;this.a=a.V();this.de=-1;this.P=this.$="";this.g=null}f(){this.a=null}Cg(a){this.de=a}Kg(a){this.$=a}o(){return this.a.createGain()}O(){}R(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.a.currentTime;f+=n;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Ta(){return{type:this.P,tag:this.$,params:this.g}}}
self.Ae=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.P="filter";this.g=[b,d,f,n,q,v];this.l=this.o();this.c=this.o();this.c.gain.value=v;this.b=this.o();this.b.gain.value=1-v;this.A=this.a.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=f;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c)}f(){this.l.disconnect();this.A.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();
this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b,d,f);this.m(this.b.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,f)}}};self.ye=class extends g{constructor(a,b,d,f){super(a);this.P="delay";this.g=[b,d,f];this.l=
this.o();this.c=this.o();this.c.gain.value=f;this.b=this.o();this.b.gain.value=1-f;this.nb=this.o();this.T=this.a.createDelay(b);this.T.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.b);this.nb.connect(this.c);this.nb.connect(this.T);this.T.connect(this.eb);this.eb.connect(this.nb)}f(){this.l.disconnect();this.c.disconnect();this.b.disconnect();this.nb.disconnect();this.T.disconnect();this.eb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);
this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,f){const n=self.ea.sd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.c.gain,b,d,f);this.m(this.b.gain,1-b,d,f);break;case 4:this.g[1]=n(b);this.m(this.eb.gain,n(b),d,f);break;case 5:this.g[0]=b,this.m(this.T.delayTime,b,d,f)}}};self.xe=class extends g{constructor(a,b,d,f){super(a);this.P="convolution";this.g=[d,f];this.Vd=this.Ud="";this.l=this.o();this.c=this.o();this.c.gain.value=f;this.b=this.o();this.b.gain.value=
1-f;this.cb=this.a.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.b);this.cb.connect(this.c)}f(){this.l.disconnect();this.cb.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.c.gain,b,d,f),this.m(this.b.gain,1-b,d,f)}}xg(a,b){this.Ud=a;this.Vd=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Ud;a.bufferUrl="";a.bufferType=this.Vd;return a}};self.Be=class extends g{constructor(a,b,d,f,n,q){super(a);this.P="flanger";this.g=[b,d,f,n,q];this.l=this.o();this.b=this.o();this.b.gain.value=1-q/2;this.c=this.o();this.c.gain.value=q/2;this.gb=this.o();this.gb.gain.value=n;this.T=this.a.createDelay(b+d);this.T.delayTime.value=b;this.u=this.a.createOscillator();this.u.frequency.value=f;this.H=this.o();this.H.gain.value=d;this.l.connect(this.T);this.l.connect(this.b);
this.T.connect(this.c);this.T.connect(this.gb);this.gb.connect(this.T);this.u.connect(this.H);this.H.connect(this.T.delayTime);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.T.disconnect();this.u.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();this.gb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.c.gain,
b/2,d,f);this.m(this.b.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,f)}}};self.De=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.P="phaser";this.g=[b,d,f,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=1-v/2;this.c=this.o();this.c.gain.value=v/2;this.A=this.a.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=f;this.u=this.a.createOscillator();this.u.frequency.value=q;this.H=this.o();this.H.gain.value=n;this.l.connect(this.A);this.l.connect(this.b);this.A.connect(this.c);this.u.connect(this.H);this.H.connect(this.A.frequency);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.c.gain,b/2,d,f);this.m(this.b.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,f)}}};self.Ce=class extends g{constructor(a,b){super(a);this.P="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,f){const n=self.ea.sd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,f)}}};self.Fe=class extends g{constructor(a,b,d){super(a);this.P="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.a.createOscillator();this.u.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.u.connect(this.H);this.H.connect(this.h.gain);this.u.start(0)}f(){this.u.stop(0);this.u.disconnect();
this.H.disconnect();this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.H.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,f)}}};self.Ee=class extends g{constructor(a,b,d){super(a);this.P="ringmod";this.g=[b,d];this.l=this.o();this.c=this.o();this.c.gain.value=d;this.b=this.o();this.b.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.u=this.a.createOscillator();this.u.frequency.value=b;this.u.connect(this.tb.gain);this.u.start(0);this.l.connect(this.tb);this.l.connect(this.b);this.tb.connect(this.c)}f(){this.u.stop(0);this.u.disconnect();this.tb.disconnect();this.l.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.c.gain,b,d,f);
this.m(this.b.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,f)}}};self.ze=class extends g{constructor(a,b,d,f,n,q){super(a);this.P="distortion";this.g=[b,d,f,n,q];this.l=this.o();this.fc=this.o();this.ec=this.o();this.yg(f,n);this.c=this.o();this.c.gain.value=q;this.b=this.o();this.b.gain.value=1-q;this.kc=this.a.createWaveShaper();this.Vc=new Float32Array(65536);this.Af(b,d);this.kc.curve=this.Vc;this.l.connect(this.fc);this.l.connect(this.b);this.fc.connect(this.kc);this.kc.connect(this.ec);
this.ec.connect(this.c)}f(){this.l.disconnect();this.fc.disconnect();this.kc.disconnect();this.ec.disconnect();this.c.disconnect();this.b.disconnect();super.f()}yg(a,b){.01>a&&(a=.01);this.fc.gain.value=a;this.ec.gain.value=Math.pow(1/a,.6)*b}Af(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.Mg(f,a,b);this.Vc[32768+d]=f;this.Vc[32768-d-1]=-f}}Mg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.ea.bh(f-b,1/d))*(0>a?-1:1)}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();
this.b.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.c.gain,b,d,f),this.m(this.b.gain,1-b,d,f)}}};self.we=class extends g{constructor(a,b,d,f,n,q){super(a);this.P="compressor";this.g=[b,d,f,n,q];this.h=this.a.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.ve=class extends g{constructor(a,b,d){super(a);this.P="analyser";this.g=[b,d];this.h=this.a.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.ae=new Float32Array(this.h.frequencyBinCount);this.oe=new Uint8Array(b);this.me=this.Ma=0;this.j.hf(this)}f(){this.j.qg(this);this.h.disconnect();super.f()}Da(){this.h.getFloatFrequencyData(this.ae);this.h.getByteTimeDomainData(this.oe);const a=this.h.fftSize;let b=this.Ma=0;for(var d=0;d<a;++d){let f=(this.oe[d]-128)/128;0>f&&(f=-f);
this.Ma<f&&(this.Ma=f);b+=f*f}d=self.ea.Xe;this.Ma=d(this.Ma);this.me=d(Math.sqrt(b/a))}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}Qe(){return{tag:this.$,index:this.de,peak:this.Ma,rms:this.me,binCount:this.h.frequencyBinCount,freqBins:this.ae}}}};
