const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Bullet: 0},
	{Sprinter: 0},
	{Solid: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Spike: 0},
	{Sine: 0},
	{Sine2: 0},
	{TitleName: 0},
	{StartButton: 0},
	{Keyboard: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{TopologyOrb: 0},
	{FinishLine: 0},
	{WinningText: 0},
	{Retry: 0},
	{MainMenu: 0},
	{Text: 0},
	{Text2: 0},
	{InstructionsButton: 0},
	{Text3: 0},
	{Sprite: 0},
	{TopologyOrb2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{LevelButton: 0},
	{Text4: 0},
	{Spirnterpng: 0},
	{Level1Button: 0},
	{Text5: 0}
];

self.InstanceType = {
	Sprinter: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	TitleName: class extends self.ITextInstance {},
	StartButton: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TopologyOrb: class extends self.ISpriteInstance {},
	FinishLine: class extends self.ISpriteInstance {},
	WinningText: class extends self.ITextInstance {},
	Retry: class extends self.IButtonInstance {},
	MainMenu: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	InstructionsButton: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TopologyOrb2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	LevelButton: class extends self.IButtonInstance {},
	Text4: class extends self.ITextInstance {},
	Spirnterpng: class extends self.ISpriteInstance {},
	Level1Button: class extends self.IButtonInstance {},
	Text5: class extends self.ITextInstance {}
}