function k(b,a,c,d){b.v.Bb(b.hb,a,c,d,void 0)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.we()._OnMessageFromDOM({type:"event",component:b.hb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.v.C(b.hb,a,c)}function ba(b,a){for(const [c,d]of a)aa(b,c,d)}function p(b){b.Nb||(b.v.hd(b.Pd),b.Nb=!0)}window.ic=class{constructor(b,a){this.v=b;this.hb=a;this.Nb=!1;this.Pd=()=>this.Ka()}Zc(){}Ka(){}};
window.df=class{constructor(){this.Wc=-1}j(){-1!==this.Wc&&(self.clearTimeout(this.Wc),this.Wc=-1)}};"use strict";class ca{constructor(b){this.Ec=b;this.Hc=!1;this.Oc=!0}}function da(b,a){const c=a.elementId,d=b.cd(c,a),e=new ca(d);b.kb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Oc=!!a.isVisible;a=b.uc(d);a.addEventListener("focus",()=>{ea(b,"elem-focused",c)});a.addEventListener("blur",()=>{ea(b,"elem-blurred",c)});b.Jb&&document.body.appendChild(d)}
function fa(b,a){aa(b,"get-element",c=>{const d=t(b,c.elementId);return a(d,c)})}function t(b,a){b=b.kb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ec}function ea(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.he=class extends self.ic{constructor(b){super(b,"button");this.kb=new Map;this.Jb=!0;ba(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=t(this,a);this.Jb&&c.parentElement.removeChild(c);this.kb.delete(a)}],["set-visible",a=>{if(this.Jb){var c=this.kb.get(a.elementId),d=c.Ec;c.Hc?d.style.display=a.isVisible?"":"none":c.Oc=!!a.isVisible}}],["update-position",a=>{if(this.Jb){var c=this.kb.get(a.elementId),d=c.Ec;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Hc||(c.Hc=!0,c.Oc&&(d.style.display=""))}}],["update-state",a=>{const c=t(this,a.elementId);this.rc(c,a)}],["focus",a=>{const c=this.uc(t(this,a.elementId));a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=t(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{t(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{t(this,
a.elementId).removeAttribute(a.name)}]]);fa(this,a=>a)}cd(){throw Error("required override");}rc(){throw Error("required override");}uc(b){return b}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent),ia=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ja=0;
function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ue?new Promise(c=>{const d="c3_resolve_"+ja;++ja;self[d]=c;a.textContent=b.Ye+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ma=!1,na=!1;function oa(){if(!ma){try{new Worker("blob://",{get type(){na=!0}})}catch(b){}ma=!0}return na}let w=new Audio;
const pa={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function qa(b){b=await ra(b);return(new TextDecoder("utf-8")).decode(b)}
function ra(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const y=[];let z=0;window.RealFile=window.File;const A=[],D=new Map,E=new Map;let sa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.Db=class b{constructor(a){this.ca=a.$e;this.va=null;this.ba="";this.Xa=a.Xe;this.yb={};this.Qa=this.ta=null;this.Lb=[];this.J=this.wa=null;this.Lc=!1;this.wd=0;this.nb=null;this.Wa=-1;this.Pe=()=>this.De();this.Va=[];this.B=a.Qd;this.Ob="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&oa()||(this.ca=!1);this.ca&&ia&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(u){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Rb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.ze(c));this.C("runtime","create-job-worker",()=>this.Ae());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.ld(a)):this.ld(a)}j(){this.sc();this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}le(){return ha&&"cordova"===this.B}nc(){const a=navigator.userAgent;return ha&&ua.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}je(){return u}ed(){return u&&ua.has(this.B)}async ld(a){"macos-wkwebview"===this.B&&this.Ie();if("playable-ad"===this.B){this.qa=
self.c3_base64files;this.Rb={};await this.se();for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Rb.hasOwnProperty(c)?a.Za[d]={Ue:!0,Ye:this.Rb[c]}:this.qa.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.qa[c]))}a.dc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.hd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.We?this.ba=a.We:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.bf&&(this.yb=a.bf);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ce(d));this.nb=new self.me(this);await wa(this.nb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.ye(a,c.port2):await this.xe(a,c.port2)}vc(a){a=this.yb.hasOwnProperty(a)?this.yb[a]:a.endsWith("/workermain.js")&&this.yb.hasOwnProperty("workermain.js")?this.yb["workermain.js"]:"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async hc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Ob)return a=await this.zb(d.Te?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}kd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ia(),g=window.devicePixelRatio,h=b.cb(),m=a.hf,q=window.cr_previewImageBlobs||this.qa,n=window.cr_previewProjectFileBlobs,B=window.cr_previewProjectFiles,x=window.ff||
"";a=a.Qd;var r=(new URLSearchParams(self.location.search)).has("debug"),C=this.nb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:n,previewProjectFileSWUrls:B,swClientId:x,exportType:a,isDebug:r,ife:!!self.gf,jobScheduler:{inputPort:C.Kc,outputPort:C.Sc,maxNumWorkers:C.Me},supportedAudioFormats:pa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Ob,isiOSCordova:this.le(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ye(a,c){const d=this.vc(a.af);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=n=>{this.ta.removeEventListener("message",q);n.data&&"ok"===n.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.hc(d,this.ba,{type:"module",name:"Runtime",Te:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.dc||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.cc.length;h<m;++h){const q=
a.cc[h],n=q[0];if(n===a.Xc||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q[1]=await this.La(n)}this.ta.postMessage(Object.assign(this.kd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.cc,mainProjectScript:a.Xc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...xa(this.nb)]);this.Lb=A.map(h=>new h(this));this.jd();ya(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.v.gd(q.hb,"js-invoke-function",
{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Bb("runtime","go-to-last-error-script"))}async xe(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=A.map(g=>new g(this));this.jd();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.dc)&&d.unshift(...a.dc);d=await Promise.all(d.map(g=>
this.La(g)));await Promise.all(d.map(g=>v(g)));d=self.C3_ProjectScriptsStatus;const e=a.Xc,f=a.cc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await v(h),"preview"!==this.B||d[g]||this.nd(g,"main script did not run to completion")}catch(m){this.nd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await v(h);"preview"===this.B&&"object"!==typeof self.cf.ef?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:ta}),ya(this.wa),this.md(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}nd(a,c){this.Gb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}md(){this.Gb()}Gb(){const a=
window.Re;a&&(a.parentElement.removeChild(a),window.Re=null)}async Ae(){const a=await za(this.nb);return{outputPort:a,transferables:[a]}}we(){if(this.ca)throw Error("not available in worker mode");return this.Qa}Bb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}gd(a,c,d,e,f){const g=sa++,h=new Promise((m,q)=>{E.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Be(a);if("result"===c)this.Ee(a);else if("runtime-ready"===c)this.Fe();else if("alert-error"===c)this.Gb(),alert(a.message);else if("creating-runtime"===c)this.md();else throw Error(`unknown message '${c}'`);}Be(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Fb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Fb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Fb(f,!1,""+h)}):this.Fb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Fb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ee(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}C(a,
c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ec(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}jd(){for(const a of this.Lb)if("runtime"===a.hb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Ce(a){this.Bb("debugger","message",a)}Fe(){for(const a of this.Lb)a.Zc()}static cb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
va)}static od(a){va=!!a}hd(a){this.Va.push(a);this.Ac()}He(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.sc()}Ac(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Pe))}sc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}De(){this.Wa=-1;for(const a of this.Va)a();this.Ac()}Ba(a){this.wa.Ba(a)}Ja(a){this.wa.Ja(a)}zc(){this.wa.zc()}Eb(a){this.wa.Eb(a)}ke(){return!!pa["audio/webm; codecs=opus"]}async Je(a){a=await this.gd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}oe(a){this.Lc=!0;this.wd=a}ie(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fd(a){return!this.ie(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Ob&&this.fd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.zb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ze(a){const c=a.filename;switch(a.as){case "text":return await this.ge(c);
case "buffer":return await this.zb(c);default:throw Error("unsupported type");}}bd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ge(a){a=await this.bd(a);return await qa(a)}tc(){if(y.length&&!(8<=z)){z++;var a=y.shift();this.te(a.filename,a.Ze,a.Se)}}zb(a){return new Promise((c,d)=>{y.push({filename:a,Ze:e=>{z--;this.tc();c(e)},Se:e=>{z--;this.tc();d(e)}});this.tc()})}async te(a,c,d){try{const e=
await this.bd(a),f=await ra(e);c(f)}catch(e){d(e)}}Ie(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async se(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.re(c,d));await Promise.all(a)}async re(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),
this.Rb[a]=c.str;else{let d=await this.ve(c);d||(d=this.ue(c));this.qa[a]=d}}async ve(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}ue(a){a=this.Ge(a);return this.qe(a.data,a.Ve)}Ge(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ve:a,data:d}}qe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const G=self.Db;
function Aa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}
function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let La=!1;document.addEventListener("pause",()=>La=!0);document.addEventListener("resume",()=>La=!1);function ya(b){b.vd=!0;b.Pc=b.v.oa();b.ob=b.v.ia()}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Oa(b){return await self.C3_GetSvgImageSize(b.blob)}function Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Qa(b){self.setTimeout(()=>{b.ud=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Ra(b,!0)),document.addEventListener("resume",()=>Ra(b,!1))):document.addEventListener("visibilitychange",()=>Ra(b,document.hidden));return{isSuspended:!(!document.hidden&&!La)}}
function Sa(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Ta(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Ua(b){await Da(b.url)}
function Va(b,a){b.xd=a.message;-1===b.Fc&&(b.Fc=setTimeout(()=>{b.Fc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.xd)},250))}function L(b){if(!b.Z){var a=G.cb();a&&"any"!==b.Uc&&Wa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ia()})}}function Xa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.cb(),innerWidth:b.oa(),innerHeight:b.ia()})}
function Ra(b,a){a?b.v.sc():b.v.Ac();k(b,"visibilitychange",{hidden:a})}function Ya(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=Ba.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function Za(b,a,c,d){b.Z||Aa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function ab(b){window!==window.top&&window.focus();bb(b.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.tb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Za(b,d,c,Ca),b.tb=c.buttons)}}
function cb(b,a,c){if(!b.Z&&!Aa(c)){var d=b.tb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.tb=c.buttons;Za(b,c.type,c,Ca)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function db(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function eb(b,a,c,d){const e=b.oa(),f=b.ia();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.cb()}):10>d&&fb(b,e,f,d+1)}
function fb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>eb(b,a,c,d),48)}
function Wa(b){b=b.Uc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.ec(class extends self.ic{constructor(b){super(b,"runtime");this.Cd=!0;this.vd=!1;this.Ya=-1;this.Uc="any";this.pd=this.qd=!1;this.$b=document.createElement("div");this.$b.className="c3-screen-reader-text";this.$b.setAttribute("aria-live","polite");document.body.appendChild(this.$b);this.Ea=null;this.Z=!1;this.xd="";this.Fc=-1;this.ud=!1;this.Pc=b.oa();this.ob=b.ia();this.da=this.xb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Lc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Cd&&(e.style.display="",this.Cd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ma(d));b.C("runtime","raster-svg-image",d=>Na(d));b.C("runtime","get-svg-image-size",
d=>Oa(d));b.C("runtime","set-target-orientation",d=>{this.Uc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Pa(d));b.C("runtime","go-to-script",d=>Pa(d));b.C("runtime","before-start-ticking",()=>Qa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Sa(this));b.C("runtime","enable-device-motion",()=>Ta(this));b.C("runtime","add-stylesheet",d=>Ua(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.$b.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.oe(d.duration)});b.C("runtime","export-to-video-progress",d=>Va(this,d));b.C("runtime","exported-to-video",d=>{window.Qe({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Qe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ha(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",
K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.tb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ka,{passive:!1});window.addEventListener("wheel",Ka,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.vd){var d=this.oa();var e=this.ia();if(this.v.ed()){if(this.ud){if(this.Pc===d&&
e<this.ob){this.xb=this.ob-e;db(this,this.ob,this.xb);d=void 0;break a}0<this.xb&&(this.xb=0,db(this,e,this.xb))}this.Pc=d;this.ob=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.cb()});this.v.nc()&&(-1!==this.Ya&&clearTimeout(this.Ya),eb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Xa(this,d));window.addEventListener("webkitfullscreenerror",d=>Xa(this,d));window.addEventListener("mozfullscreenerror",d=>Xa(this,d));if(b.nc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ha(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(G.od(!0),L(this)):"exited-fullscreen"===d?(G.od(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Tb=new WeakSet;this.ua=!1}Zc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},I);this.tb=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&k(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Ya(this,"keydown",a));window.addEventListener("keyup",a=>Ya(this,"keyup",a));window.addEventListener("dblclick",a=>Za(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{ab(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);cb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>cb(this,"pointermove",a)),window.addEventListener("mouseup",a=>cb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.zc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.je()&&!this.v.ed()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ia(){return this.v.ia()}zc(){var b=
[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Tb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");this.Tb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Tb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Tb.add(b)}Eb(b){this.ua=!!b}});"use strict";
async function wa(b){if(b.Ke)throw Error("already initialised");b.Ke=!0;var a=b.xa.vc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Dc=await b.xa.hc(a,b.gb,{name:"DispatchWorker"});a=new MessageChannel;b.Kc=a.port1;b.Dc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Sc=await za(b)}function xa(b){return[b.Kc,b.Sc]}
async function za(b){const a=b.Dd.length;var c=b.xa.vc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.hc(c,b.gb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Dc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Dd.push(c);return e.port1}
self.me=class{constructor(b){this.xa=b;this.gb=b.ba;this.gb="preview"===b.B?this.gb+"workers/":this.gb+b.Xa;this.Me=Math.min(navigator.hardwareConcurrency||2,16);this.Dc=null;this.Dd=[];this.Sc=this.Kc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Db({$e:!0,af:"workermain.js",Za:["scripts/c3runtime.js"],cc:[],Xc:"",Xe:"scripts/",dc:[],Qd:"html5"}));"use strict";const gb=180/Math.PI;
async function hb(b,a){if(a.isiOSCordova||a.isSafari)b.Wb=!0;b.Vc=a.timeScaleMode;b.Id=["equalpower","HRTF","soundfield"][a.panningModel];b.td=["linear","inverse","exponential"][a.distanceModel];b.Jd=a.refDistance;b.Hd=a.maxDistance;b.Ld=a.rolloffFactor;if(b.v.Lc)b.Wb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.wd)});else{var c={latencyHint:a.latencyHint};b.Od||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ib(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ib(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function jb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,n=a.panning,B=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Ed=g;kb(b,g);try{b.$=await lb(b,c,d,e,g,f);if(n){P(b.$,!0);var r=b.$,C=n.innerAngle,ka=n.outerAngle,la=n.outerGain;if(r.mb){mb(r,n.x,n.y,n.z,n.angle);var F=self.$a.pe;r.ra[0]!==F(C)&&(r.ra[0]=
F(C),r.F.coneInnerAngle=F(C));r.ra[1]!==F(ka)&&(r.ra[1]=F(ka),r.F.coneOuterAngle=F(ka));r.ra[2]!==la&&(r.ra[2]=la,r.F.coneOuterGain=la)}n.hasOwnProperty("uid")&&(b.$.pa=n.uid)}else"number"===typeof B&&0!==B?(Q(b.$,!0),nb(b.$,B)):(P(b.$,!1),Q(b.$,!1));b.$.Play(h,m,q,x)}catch(yb){console.error("[Construct] Audio: error starting playback: ",yb);return}finally{c=b.vb.get(g);if(!c)throw Error("expected pending tag");c.Yc--;0===c.Yc&&(c.resolve(),b.vb.delete(g))}p(b)}
async function ob(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await pb(b,c);for(const n of R(b,c)){c=n;var f=d,g=e,h=a;if(!c.Pa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ha=f;c.Oa=g;c.Nd=h}}S(b)}async function qb(b,a){const c=a.tag;a=a.rate;await pb(b,c);for(const d of R(b,c))b=d,b.ma!==a&&(b.ma=a,b.Ca())}
async function rb(b,a){const c=a.tag;a=a.pos;await pb(b,c);for(const d of R(b,c))d.oc(a)}async function sb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await lb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function tb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function ub(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Wd(b,...e);else if("delay"===c)e=new self.Ud(b,...e);else if("convolution"===c){c=null;try{c=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Td(b,c.ja,...e);var f=a.bufferType;c.rd=a.bufferOriginalUrl;c.sd=f}else if("flanger"===c)e=new self.Xd(b,...e);else if("phaser"===c)e=new self.Zd(b,...e);else if("gain"===c)e=
new self.Yd(b,...e);else if("stereopan"===c)e=new self.ae(b,...e);else if("tremolo"===c)e=new self.be(b,...e);else if("ringmod"===c)e=new self.$d(b,...e);else if("distortion"===c)e=new self.Vd(b,...e);else if("compressor"===c)e=new self.Sd(b,...e);else if("analyser"===c)e=new self.Rd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.la.get(d);e||(e=[],b.la.set(d,e));a.Bd=e.length;a.ga=d;e.push(a);vb(b,d);wb(b)}
async function xb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.I)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.I=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.ac=a.timeScale;b.Gc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.ua=a.isSilent;b.v.Eb(b.ua);b.Sb=a.masterVolume;b.Na.gain.value=
b.Sb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>ub(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>zb(b,f,c)));S(b)}
async function Ab(b,a){try{const c=b.g.suspend(a.time);b.Ad?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Bb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Bb(d)),b.Ad=!0);await c}catch(c){Bb(c)}}
function ib(b){b.Mb||(b.Jc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Mb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.bb()===c)return await Cb(g),g;if(f)return null;if(e&&(b.Wb||b.zd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Od;e&&f&&(b.zd=!0);c=!e||b.Wb||f?new self.ee(b,a,c,d,e,f):new self.ce(b,a,c,d,e);b.ka.push(c);await Cb(c);b.Gd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Gd.add(a));return c}
function Eb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.na()}function vb(b,a){let c=b.na();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of R(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Qc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*R(b,a){if(a)for(const c of b.I)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Fb(b,a,c){return c?b.v.Je(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.I.length;d<e;++d){const f=b.I[d];b.I[c]=f;f.O===a?f.j():++c}b.I.length=c}
async function lb(b,a,c,d,e,f){for(const g of b.I)if(g.bb()===c&&(g.fc()||f))return g.ga=e,g;a=await O(b,a,c,d,f);e="html5"===a.Bc?new self.de(a.s,a,e):new self.fe(a.s,a,e);b.I.push(e);return e}function kb(b,a){let c=b.vb.get(a);if(!c){let d=null;c={Yc:0,promise:new Promise(e=>d=e),resolve:d};b.vb.set(a,c)}c.Yc++}function pb(b,a){a||(a=b.Ed);return(b=b.vb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)p(b);else for(const a of b.I)if(!a.H&&!a.U()){p(b);break}}
function Hb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function wb(b){b.Mc||(b.Mc=!0,Promise.resolve().then(()=>Ib(b)))}function Ib(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.ab());k(b,"fxstate",{fxstate:a});b.Mc=!1}
async function zb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,n=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await lb(b,d,e,f,h,g)}catch(B){console.error("[Construct] Audio: error loading audio state: ",B);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),nb(b,d));c.Play(m,q,n,0);a.isPlaying||c.eb();c.xc(a)}}}function Bb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.ic{constructor(b){super(b,"audio");this.Na=this.g=null;this.Mb=this.Jc=!1;this.ya=()=>{if(!this.Jc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Mb&&(this.Jc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Mb=!1)}};this.ka=[];this.I=[];this.$=null;this.Ed="";this.Gd=new Set;this.Fd=-1;this.vb=new Map;this.Sb=1;this.ua=!1;this.Vc=0;this.ac=1;this.Gc=0;this.Id="HRTF";this.td="inverse";this.Jd=600;this.Hd=1E4;this.Ld=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.zd=this.Wb=!1;this.Od=this.v.ke();this.la=new Map;this.Ma=new Set;this.Ad=this.Mc=!1;this.Qc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Qc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Eb(this,this.Qc))};this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.Na.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;ba(this,[["create-audio-context",a=>hb(this,a)],["play",a=>jb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.I)a.Aa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.eb():d.Cb();S(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>ob(this,a)],["set-master-volume",a=>{this.Sb=a.vol;this.Na.gain.value=this.Sb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Jb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Eb(this.ua);for(const c of this.I)c.Hb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.pc(a)}],["set-playback-rate",a=>qb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of R(this,
c))Q(d,!0),nb(d,a)}],["seek",a=>rb(this,a)],["preload",a=>sb(this,a)],["unload",a=>tb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.I)c.qc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ub(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.la.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),wb(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.la.get(a);if(c&&c.length){for(const d of c)d.j();this.la.delete(a);vb(this,a)}}],["tick",a=>{this.ac=a.timeScale;this.Gc=a.gameTime;this.Fd=a.tickCount;if(0!==this.Vc)for(var c of this.I)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==
c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.I)e.pa===a&&mb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>xb(this,a)],["offline-render-audio",a=>Ab(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Na}Ab(){return this.ua}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();b=this.g.currentTime;for(var a of this.I)a.Ka(b);
a=this.I.filter(c=>!c.H&&!c.U()).map(c=>c.ab());k(this,"state",{tickCount:this.Fd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.ga,index:c.Bd,peak:c.Ua,rms:c.Kd,binCount:c.l.frequencyBinCount,freqBins:c.yd}))});0===a.length&&0===this.Ma.size&&this.Nb&&(this.v.He(this.Pd),this.Nb=!1)}static pe(b){return b*gb}static dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ne(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.Db.ec(self.$a);
"use strict";function Cb(b){b.Qb||(b.Qb=b.wc());return b.Qb}self.$c=class{constructor(b,a,c,d,e){this.s=b;this.Oe=a;this.Ga=c;this.R=d;this.Le=e;this.Bc="";this.Qb=null}j(){this.Qb=this.s=null}wc(){}V(){return this.s.V()}kc(){return this.Oe}bb(){return this.Ga}jc(){return this.R}za(){return this.Le}ha(){}};"use strict";
self.ce=class extends self.$c{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Bc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.pb=this.qb=null;this.M.addEventListener("canplaythrough",()=>!0);this.ub=this.V().createGain();this.sb=null;this.M.addEventListener("canplay",()=>{this.qb&&(this.qb(),this.pb=this.qb=null);!this.sb&&this.M&&(this.sb=this.V().createMediaElementSource(this.M),this.sb.connect(this.ub))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.pb&&(this.pb(f),this.pb=this.qb=null)})}j(){Gb(this.s,this);this.ub.disconnect();this.ub=null;this.sb.disconnect();this.sb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}wc(){return new Promise((b,a)=>{this.qb=b;this.pb=a;this.M.src=this.Ga})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Kb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.B&&a.fd(b.Ga)&&a.Ob)b.Da=await a.zb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Lb(b){if(b.ja)return b.ja;b.ja=await Fb(b.s,b.Da,b.Ne);b.Da=null}
self.ee=class extends self.$c{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Bc="webaudio";this.ja=this.Da=null;this.Ne=!!f}j(){Gb(this.s,this);this.ja=this.Da=null;super.j()}async wc(){try{await Kb(this),await Lb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Mb=0;
function P(b,a){a=!!a;b.mb!==a&&(b.mb=a,b.mb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Id,b.F.distanceModel=b.s.td,b.F.refDistance=b.s.Jd,b.F.maxDistance=b.s.Hd,b.F.rolloffFactor=b.s.Ld),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function Q(b,a){a=!!a;b.Pb!==a&&(b.Pb=a,b.Pb?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function nb(b,a){b.Pb&&b.Tc!==a&&(b.fa.pan.value=a,b.Tc=a)}function T(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.lc()}function Jb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Hb())}
function mb(b,a,c,d,e){if(b.mb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Nc?b.s.Gc:performance.now()/1E3}
self.ad=class{constructor(b,a,c){this.s=b;this.O=a;this.ga=c;this.Ib=Mb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.mb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Pb=!1;this.Tc=0;this.H=!0;this.X=this.sa=this.K=!1;this.Ha=1;this.Pa=!1;this.ma=1;b=this.s.Vc;this.Nc=1===b&&!this.za()||2===b;this.Oa=this.pa=-1;this.Nd=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Eb(this.s,this.ga)}kc(){return this.O.kc()}bb(){return this.O.bb()}jc(){return this.O.jc()}za(){return this.O.za()}U(){}fc(){}IsPlaying(){return!this.H&&!this.K&&!this.U()}Ia(){}ha(){return this.O.ha()}Play(){}Aa(){}eb(){}Cb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Nd&&this.Aa(),Hb(this.s,"fade-ended",this.ga,this.Ib))}lc(){const b=this.Ha;return isFinite(b)?b:0}Ab(){return this.s.Ab()}Hb(){}pc(){}Ca(){}oc(){}qc(){}mc(){}ab(){var b=this.Ib,
a=this.ga,c=this.ha(),d=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ma,uid:this.pa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.za(),isLooping:this.X,isMuted:this.Pa,resumePosition:this.mc(),pan:f,stereoPan:this.fa?this.Tc:
null}}xc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Jb(this,b.isMuted)}};"use strict";
self.de=class extends self.ad{constructor(b,a,c){super(b,a,c);this.O.ub.connect(this.G);this.O.onended=()=>this.yc()}j(){this.Aa();this.O.ub.disconnect();super.j()}T(){return this.O.T()}yc(){this.H=!0;this.pa=-1;Hb(this.s,"ended",this.ga,this.Ib)}U(){return this.T().ended}fc(){return this.H?!0:this.U()}Ia(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.bb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.H=!1;this.X=b;this.ma=1}Aa(){const b=this.T();b.paused||b.pause();this.s.Ja(b);this.H=!0;this.K=!1;this.pa=-1}eb(){if(!(this.K||this.H||this.U())){var b=this.T();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Cb(){!this.K||this.H||this.U()||(this.s.Ba(this.T()),this.K=!1)}Hb(){this.T().muted=this.Pa||this.Ab()}pc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ca(){let b=this.ma;this.Nc&&(b*=this.s.ac);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}oc(b){if(!this.H&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}mc(){return this.Ia()}qc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ba(this.T()),this.sa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.fb=null}
self.fe=class extends self.ad{constructor(b,a,c){super(b,a,c);this.o=null;this.Ub=d=>this.yc(d);this.Ic=!0;this.fb=null;this.P=this.Vb=this.Xb=0;this.Rc=1}j(){this.Aa();V(this);this.Ub=null;super.j()}yc(b){this.K||this.sa||b.target!==this.fb||(this.H=this.Ic=!0,this.pa=-1,V(this),Hb(this.s,"ended",this.ga,this.Ib))}U(){return!this.H&&this.o&&this.o.loop||this.K?!1:this.Ic}fc(){return!this.o||this.H?!0:this.U()}Ia(){let b;b=this.K?this.P:this.Vb+(U(this)-this.Xb)*this.ma;this.X||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Rc=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ja;this.o.connect(this.G);this.fb=this.o;this.o.onended=this.Ub;this.o.loop=b;this.o.start(d,c);this.K=this.H=this.Ic=!1;this.X=b;this.ma=1;this.Xb=U(this);this.Vb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.K=!1;this.pa=-1}eb(){this.K||this.H||this.U()||(this.P=this.Ia(),this.X&&(this.P%=this.ha()),this.K=!0,this.o.stop(0))}Cb(){!this.K||this.H||this.U()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.fb=this.o,this.o.onended=this.Ub,this.o.loop=this.X,T(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Xb=U(this),this.Vb=this.P,this.K=!1)}lc(){return super.lc()*this.Rc}Hb(){this.Rc=this.Pa||this.Ab()?0:1;T(this,this.Ha)}pc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Nc&&(b*=this.s.ac);this.o&&(this.o.playbackRate.value=b)}oc(b){this.H||this.U()||(this.K?this.P=b:(this.eb(),this.P=
b,this.Cb()))}mc(){return this.P}qc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ia(),this.X&&(this.P%=this.ha()),this.o.stop(0)):this.sa=!1:this.sa&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.fb=this.o,this.o.onended=this.Ub,this.o.loop=this.X,T(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Xb=U(this),this.Vb=this.P,this.sa=!1)}xc(b){super.xc(b);this.P=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.s=b;this.g=b.V();this.Bd=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}ab(){return{type:this.R,tag:this.ga,params:this.m}}}
self.Wd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.Ud=class extends Y{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.rb=W(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.jb=W(this);this.jb.gain.value=c;this.u.connect(this.rb);this.u.connect(this.h);this.rb.connect(this.i);this.rb.connect(this.W);this.W.connect(this.jb);this.jb.connect(this.rb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.rb.disconnect();
this.W.disconnect();this.jb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.$a.dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.jb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.W.delayTime,a,c,d)}}};
self.Td=class extends Y{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.sd=this.rd="";this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ib=this.g.createConvolver();this.ib.normalize=c;this.ib.buffer=a;this.u.connect(this.ib);this.u.connect(this.h);this.ib.connect(this.i)}j(){this.u.disconnect();this.ib.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}ab(){const b=super.ab();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.Xd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.lb=W(this);this.lb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.lb);this.lb.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.lb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.lb.gain,a/100,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.A.frequency,a,c,d)}}};self.Yd=class extends Y{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.$a.dd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ae=class extends Y{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.be=class extends Y{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.$d=class extends Y{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.wb=W(this);this.wb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.wb.gain);this.A.start(0);this.u.connect(this.wb);this.u.connect(this.h);this.wb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.wb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Vd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=W(this);this.Zb=W(this);this.Yb=W(this);b=d;.01>b&&(b=.01);this.Zb.gain.value=b;this.Yb.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.bc=this.g.createWaveShaper();this.Cc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Cc[32768+e]=f,this.Cc[32768-
e-1]=-f;this.bc.curve=this.Cc;this.u.connect(this.Zb);this.u.connect(this.h);this.Zb.connect(this.bc);this.bc.connect(this.Yb);this.Yb.connect(this.i)}j(){this.u.disconnect();this.Zb.disconnect();this.bc.disconnect();this.Yb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Sd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Rd=class extends Y{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.yd=new Float32Array(this.l.frequencyBinCount);this.Md=new Uint8Array(a);this.Kd=this.Ua=0;b=this.s;b.Ma.add(this);S(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.yd);this.l.getByteTimeDomainData(this.Md);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Md[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.ne;this.Ua=c(this.Ua);this.Kd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function Z(b){b.stopPropagation()}
self.Db.ec(class extends self.he{constructor(b){super(b)}cd(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",Z);d.addEventListener("pointerrawupdate",
Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;l(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.rc(d,a);return d}uc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}rc(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;
b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});
