function l(b,a,c,d){b.i.ma(b.O,a,c,d,void 0)}function p(b,a,c,d){b.i.o?l(b,a,c,d):b.i.qb()._OnMessageFromDOM({type:"event",component:b.O,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.g(b.O,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}window.Ia=class{constructor(b,a){this.i=b;this.O=a}Ga(){}};window.Vb=class{constructor(){}};"use strict";class ba{constructor(b){this.ta=b;this.va=!1;this.ya=!0}}
function ca(b,a){const c=a.elementId,d=b.Z(c,a),e=new ba(d);b.P.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.ya=!!a.isVisible;a=b.oa(d);a.addEventListener("focus",()=>{r(b,"elem-focused",c)});a.addEventListener("blur",()=>{r(b,"elem-blurred",c)});b.ba&&document.body.appendChild(d)}function t(b,a,c){q(b,a,d=>{const e=u(b,d.elementId);return c(e,d)})}function u(b,a){b=b.P.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ta}
function r(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function v(b,a,c,d){d||(d={});d.elementId=c;p(b,a,d)}
window.ka=class extends self.Ia{constructor(b,a){super(b,a);this.P=new Map;this.ba=!0;aa(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=u(this,c);this.Ja(d);this.ba&&d.parentElement.removeChild(d);this.P.delete(c)}],["set-visible",c=>{if(this.ba){var d=this.P.get(c.elementId),e=d.ta;d.va?e.style.display=c.isVisible?"":"none":d.ya=!!c.isVisible}}],["update-position",c=>{if(this.ba){var d=this.P.get(c.elementId),e=d.ta;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.va||(d.va=!0,d.ya&&(e.style.display=""))}}],["update-state",c=>{const d=u(this,c.elementId);this.D(d,c)}],["focus",c=>{const d=this.oa(u(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=u(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{u(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{u(this,
c.elementId).removeAttribute(c.name)}]]);t(this,"get-element",c=>c)}Z(){throw Error("required override");}Ja(){}D(){throw Error("required override");}oa(b){return b}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Lb?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Pb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let z=new Audio;
const ja={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const A=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,E=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.M=class b{constructor(a){this.o=a.Rb;this.T=null;this.m="";this.H=a.Ob;this.X={};this.Aa=this.J=null;this.ca=[];this.j=this.V=null;this.Wa=!1;this.R=null;this.G=-1;this.Gb=()=>this.xb();this.Da=[];this.h=a.Za;this.xa="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.o=!1);this.o&&da&&(this.o=!1);if("playable-ad"===this.h||"instant-games"===this.h)this.o=!1;if("cordova"===this.h&&this.o)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.ea=this.A=null;"html5"!==this.h||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.g("runtime","cordova-fetch-local-file",c=>this.tb(c));this.g("runtime","create-job-worker",()=>this.ub());"cordova"===this.h?document.addEventListener("deviceready",()=>this.Na(a)):this.Na(a)}eb(){return w&&
"cordova"===this.h}la(){const a=navigator.userAgent;return w&&pa.has(this.h)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}bb(){return x}Ka(){return x&&pa.has(this.h)}async Na(a){"macos-wkwebview"===this.h&&this.Bb();if("playable-ad"===this.h){this.A=self.c3_base64files;this.ea={};await this.mb();for(let d=0,e=a.K.length;d<e;++d){var c=a.K[d];this.ea.hasOwnProperty(c)?a.K[d]={Lb:!0,Pb:this.ea[c]}:this.A.hasOwnProperty(c)&&(a.K[d]=URL.createObjectURL(this.A[c]))}a.ha=[]}if("nwjs"===this.h&&
self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.ib(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Nb?this.m=a.Nb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Tb&&(this.X=a.Tb);c=new MessageChannel;this.T=c.port1;this.T.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.wb(d));this.R=new self.fb(this);await ra(this.R);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.sb(a,c.port2):await this.rb(a,c.port2)}pa(a){a=this.X.hasOwnProperty(a)?this.X[a]:a.endsWith("/workermain.js")&&this.X.hasOwnProperty("workermain.js")?this.X["workermain.js"]:"playable-ad"===this.h&&this.A.hasOwnProperty(a)?this.A[a]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ja(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.h&&this.xa)return a=await this.ia(d.Kb?a:this.H+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,
1)}u(){return Math.max(window.innerHeight,1)}Ma(a){var c=this.m,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.L(),k=a.Zb,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,Da=window.cr_previewProjectFiles,Ea=window.Xb||"";a=a.Za;var Fa=(new URLSearchParams(self.location.search)).has("debug"),N=this.R;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:n,
previewProjectFileSWUrls:Da,swClientId:Ea,exportType:a,isDebug:Fa,ife:!!self.Yb,jobScheduler:{inputPort:N.wa,outputPort:N.Ca,maxNumWorkers:N.Eb},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.H+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.H+"opus.wasm.wasm",isFileProtocol:this.xa,isiOSCordova:this.eb(),isiOSWebView:this.la(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async sb(a,c){const d=this.pa(a.Sb);"preview"===this.h?(this.J=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=n=>{this.J.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():k()};this.J.addEventListener("message",m);this.J.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.J=await this.ja(d,this.m,{type:"module",name:"Runtime",Kb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ha||[],g=a.K;f=await Promise.all(f.map(h=>this.F(h)));g=await Promise.all(g.map(h=>this.F(h)));if("cordova"===this.h)for(let h=0,k=a.ga.length;h<k;++h){const m=a.ga[h],n=m[0];if(n===a.Fa||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.F(n)}this.J.postMessage(Object.assign(this.Ma(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ga,
mainProjectScript:a.Fa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...sa(this.R)]);this.ca=C.map(h=>new h(this));this.La();ta(this.V);self.c3_callFunction=(h,k)=>{var m=this.V;return m.i.gb(m.O,{name:h,params:k})};"preview"===this.h&&(self.goToLastErrorScript=()=>this.ma("runtime","go-to-last-error-script"))}async rb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.ca=C.map(g=>new g(this));this.La();var d=a.K.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);Array.isArray(a.ha)&&d.unshift(...a.ha);d=await Promise.all(d.map(g=>this.F(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Fa,f=a.ga;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.F(h),await y(h),"preview"!==this.h||d[g]||this.Pa(g,"main script did not run to completion")}catch(k){this.Pa(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=
await this.F(h),await y(h);"preview"===this.h&&"object"!==typeof self.Ub.Wb?(this.aa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ma(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:oa}),ta(this.V),this.Oa(),this.Aa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Aa,
a))}Pa(a,c){this.aa();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Oa(){this.aa()}aa(){const a=window.Ib;a&&(a.parentElement.removeChild(a),window.Ib=null)}async ub(){const a=await ua(this.R);return{outputPort:a,transferables:[a]}}qb(){if(this.o)throw Error("not available in worker mode");return this.Aa}ma(a,c,d,e,f){this.T.postMessage({type:"event",
component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}gb(a,c){const d=na++,e=new Promise((f,g)=>{E.set(d,{resolve:f,reject:g})});this.T.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.vb(a);if("result"===c)this.yb(a);else if("runtime-ready"===c)this.zb();else if("alert-error"===c)this.aa(),alert(a.message);else if("creating-runtime"===c)this.Oa();
else throw Error(`unknown message '${c}'`);}vb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.$(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.$(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.$(f,!1,""+h)}):this.$(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}$(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.T.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}yb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}g(a,c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Y(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}La(){for(const a of this.ca)if("runtime"===a.O){this.V=a;return}throw Error("cannot find runtime DOM handler");
}wb(a){this.ma("debugger","message",a)}zb(){for(const a of this.ca)a.Ga()}static L(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static Qa(a){qa=!!a}ib(a){this.Da.push(a);this.ra()}ra(){-1===this.G&&this.Da.length&&(this.G=requestAnimationFrame(this.Gb))}kb(){-1!==this.G&&(cancelAnimationFrame(this.G),this.G=-1)}xb(){this.G=-1;for(const a of this.Da)a();this.ra()}qa(){this.V.qa()}hb(){this.Wa=!0}ab(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}cb(a){return!this.ab(a)}async F(a){return"cordova"===this.h&&(a.startsWith("file:")||this.xa&&this.cb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ia(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async tb(a){const c=a.filename;switch(a.as){case "text":return await this.$a(c);case "buffer":return await this.ia(c);default:throw Error("unsupported type");}}Ha(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async $a(a){a=await this.Ha(a);return await la(a)}na(){if(A.length&&!(8<=B)){B++;var a=A.shift();this.nb(a.filename,a.Qb,a.Jb)}}ia(a){return new Promise((c,d)=>{A.push({filename:a,Qb:e=>{B--;this.na();c(e)},Jb:e=>{B--;this.na();d(e)}});this.na()})}async nb(a,c,d){try{const e=await this.Ha(a),f=await ma(e);c(f)}catch(e){d(e)}}Bb(){var a={type:"ready"};if("windows-webview2"===this.h)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.h)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async mb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.lb(c,d));await Promise.all(a)}async lb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ea[a]=c.str;else{let d=await this.pb(c);d||(d=this.ob(c));this.A[a]=d}}async pb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}ob(a){a=this.Ab(a);return this.jb(a.data,a.Mb)}Ab(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Mb:a,data:d}}jb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const F=self.M;function va(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},H={dispatchRuntimeEvent:!0};
function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}
function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function J(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let L=!1;document.addEventListener("pause",()=>L=!0);document.addEventListener("resume",()=>L=!1);function ta(b){b.Ua=!0;b.za=b.i.v();b.S=b.i.u()}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.Ta=!0},1E3);"cordova"===b.i.h?(document.addEventListener("pause",()=>O(b,!0)),document.addEventListener("resume",()=>O(b,!1))):document.addEventListener("visibilitychange",()=>O(b,document.hidden));return{isSuspended:!(!document.hidden&&!L)}}
function Oa(b){b.Sa||(b.Sa=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function Pa(b){b.Ra||(b.Ra=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function Qa(b){await ya(b.url)}
function Ra(b,a){b.Va=a.message;-1===b.ua&&(b.ua=setTimeout(()=>{b.ua=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Va)},250))}function P(b){if(!b.l){var a=F.L();a&&"any"!==b.Ea&&Sa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}function Q(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:F.L(),innerWidth:b.v(),innerHeight:b.u()})}
function O(b,a){a?b.i.kb():b.i.ra();l(b,"visibilitychange",{hidden:a})}function Ta(b,a,c){"Backspace"===c.key&&K(c);if(!b.l){var d=wa.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function R(b,a,c,d){b.l||va(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function S(b){window!==window.top&&window.focus();Ua(b.target)&&document.activeElement&&!Ua(document.activeElement)&&document.activeElement.blur()}
function T(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.U);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},G);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),R(b,d,c,xa),b.U=c.buttons)}}
function U(b,a,c){if(!b.l&&!va(c)){var d=b.U;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);b.U=c.buttons;R(b,c.type,c,xa)}}
function V(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function W(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Va(b,a,c,d){const e=b.v(),f=b.u();b.I=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.L()}):10>d&&Wa(b,e,f,d+1)}
function Wa(b,a,c,d){-1!==b.I&&clearTimeout(b.I);b.I=setTimeout(()=>Va(b,a,c,d),48)}
function Sa(b){b=b.Ea;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ua(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.Y(class extends self.Ia{constructor(b){super(b,"runtime");this.Xa=!0;this.Ua=!1;this.I=-1;this.Ea="any";this.Ra=this.Sa=!1;this.fa=document.createElement("div");this.fa.className="c3-screen-reader-text";this.fa.setAttribute("aria-live","polite");document.body.appendChild(this.fa);this.C=null;this.l=!1;this.Va="";this.ua=-1;this.Ta=!1;this.za=b.v();this.S=b.u();this.s=this.W=0;b.g("canvas","update-size",d=>{var e=this.i;e.Wa||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",
e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Xa&&(e.style.display="",this.Xa=!1))});b.g("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.g("runtime","load-webfonts",d=>Ja(d));b.g("runtime","raster-svg-image",d=>Ka(d));b.g("runtime","get-svg-image-size",
d=>La(d));b.g("runtime","set-target-orientation",d=>{this.Ea=d.targetOrientation});b.g("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.g("runtime","post-to-debugger",d=>Ma(d));b.g("runtime","go-to-script",d=>Ma(d));b.g("runtime","before-start-ticking",()=>Na(this));b.g("runtime","debug-highlight",d=>{if(d.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.C&&(this.C.style.display="none")});b.g("runtime","enable-device-orientation",()=>Oa(this));b.g("runtime","enable-device-motion",()=>Pa(this));b.g("runtime","add-stylesheet",d=>Qa(d));b.g("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.g("runtime","alert",d=>{alert(d.message)});b.g("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fa.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.g("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.g("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.hb()});b.g("runtime","export-to-video-progress",d=>Ra(this,d));b.g("runtime","exported-to-video",d=>{window.Hb({type:"exported-video",
blob:d.blob,time:d.time})});b.g("runtime","exported-to-image-sequence",d=>{window.Hb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||J(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",
K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.U=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Ua){var d=this.v();var e=this.u();if(this.i.Ka()){if(this.Ta){if(this.za===d&&e<
this.S){this.W=this.S-e;W(this,this.S,this.W);d=void 0;break a}0<this.W&&(this.W=0,W(this,e,this.W))}this.za=d;this.S=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.L()});this.i.la()&&(-1!==this.I&&clearTimeout(this.I),Va(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>P(this));window.addEventListener("webkitfullscreenchange",()=>P(this));window.addEventListener("mozfullscreenchange",()=>P(this));window.addEventListener("fullscreenerror",
d=>Q(this,d));window.addEventListener("webkitfullscreenerror",d=>Q(this,d));window.addEventListener("mozfullscreenerror",d=>Q(this,d));if(b.la())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):J(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(F.Qa(!0),P(this)):"exited-fullscreen"===d?(F.Qa(!1),P(this)):console.warn("Unknown wrapper message: ",d)};this.Ba=new Set;this.Fb=new WeakSet;this.Db=!1}Ga(){window.addEventListener("focus",()=>{l(this,"window-focus",null,H)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},H);this.U=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||J(a))&&l(this,"keyboard-blur",null,H)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("dblclick",a=>R(this,"dblclick",a,G));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{S(a);T(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{T(this,"pointermove",a)}):window.addEventListener("pointermove",a=>T(this,"pointermove",a)),window.addEventListener("pointerup",a=>T(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>T(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{S(a);U(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>U(this,"pointermove",a)),window.addEventListener("mouseup",a=>U(this,"pointerup",a)),window.addEventListener("touchstart",a=>{S(a);V(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>V(this,"pointermove",a)),window.addEventListener("touchend",a=>V(this,"pointerup",a)),window.addEventListener("touchcancel",a=>V(this,"pointercancel",a)));const b=
()=>this.qa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.bb()&&!this.i.Ka()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{W(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}qa(){var b=
[...this.Ba];this.Ba.clear();if(!this.Db)for(const a of b)(b=a.play())&&b.catch(()=>{this.Fb.has(a)||this.Ba.add(a)})}});"use strict";async function ra(b){if(b.Cb)throw Error("already initialised");b.Cb=!0;var a=b.B.pa(("playable-ad"===b.B.h?b.B.H:"")+"dispatchworker.js");b.sa=await b.B.ja(a,b.N,{name:"DispatchWorker"});a=new MessageChannel;b.wa=a.port1;b.sa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ca=await ua(b)}function sa(b){return[b.wa,b.Ca]}
async function ua(b){const a=b.Ya.length;var c=b.B.pa(("playable-ad"===b.B.h?b.B.H:"")+"jobworker.js");c=await b.B.ja(c,b.N,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.sa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ya.push(c);return e.port1}
self.fb=class{constructor(b){this.B=b;this.N=b.m;this.N="preview"===b.h?this.N+"workers/":this.N+b.H;this.Eb=Math.min(navigator.hardwareConcurrency||2,16);this.sa=null;this.Ya=[];this.Ca=this.wa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.M({Rb:!0,Sb:"workermain.js",K:["scripts/c3runtime.js"],ga:[],Fa:"",Ob:"scripts/",ha:[],Za:"html5"}));"use strict";function X(b){b.stopPropagation()}
self.M.Y(class extends self.ka{constructor(b){super(b,"button")}Z(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",X);d.addEventListener("pointermove",
X);d.addEventListener("pointerrawupdate",X);d.addEventListener("pointerup",X);d.addEventListener("mousedown",X);d.addEventListener("mouseup",X);d.addEventListener("keydown",X);d.addEventListener("keyup",X);c.addEventListener("click",()=>v(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.D(d,a);return d}oa(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}D(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;
c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";function Xa(b,a,c){Y(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.da=!0}function Y(b,a,c){a.src&&a.src.startsWith("blob:")&&b.da&&URL.revokeObjectURL(a.src);a.src=c}
self.M.Y(class extends self.ka{constructor(b){super(b,"iframe");this.da=!1;t(this,"navigate-url",(a,c)=>{Y(this,a,c.url);this.da=!1});t(this,"display-html",(a,c)=>Xa(this,a,c))}Z(b,a){b=document.createElement("iframe");b.style.position="absolute";b.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(b.setAttribute("noresize","noresize"),b.setAttribute("scrolling","no"));a.isVisible||
(b.style.display="none");a.id&&(b.id=a.id);a.allow&&(b.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&b.setAttribute("allowfullscreen",""));a.enableSandbox&&b.setAttribute("sandbox",a.sandbox);a.url?b.src=a.url:a.html&&Xa(this,b,a);return b}D(){}Ja(b){Y(this,b,"");this.da=!1}});"use strict";function Z(b){b.stopPropagation()}function Ya(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.M.Y(class extends self.ka{constructor(b){super(b,"text-input");t(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Z(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",
Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Ya);c.addEventListener("keyup",Ya);c.addEventListener("click",e=>{e.stopPropagation();v(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();v(this,"dblclick",b)});c.addEventListener("input",()=>r(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.D(c,a);return c}D(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});
