const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Audio,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{"8Direction": 0},
	{BoundTo: 0},
	{bear: 0},
	{targetid: 0},
	{chesse: 0},
	{score: 0},
	{Text: 0},
	{Button: 0},
	{Sprite: 0},
	{Text2: 0},
	{Text3: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Text4: 0},
	{Button2: 0},
	{TiledBackground5: 0},
	{Button3: 0},
	{ID: 0},
	{next: 0},
	{waypoint: 0},
	{target: 0},
	{Bullet: 0},
	{Wrap: 0},
	{rodent: 0},
	{Sprite2: 0},
	{Audio: 0},
	{door: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	bear: class extends self.ISpriteInstance {},
	chesse: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Button3: class extends self.IButtonInstance {},
	waypoint: class extends self.ISpriteInstance {},
	rodent: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	door: class extends self.ISpriteInstance {}
}