const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{Text2: 0},
	{Button: 0},
	{Button2: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{roadBlock: 0},
	{Ttext1: 0},
	{Text4: 0},
	{LText1: 0},
	{Text5: 0},
	{retry: 0},
	{Cowerd: 0},
	{PHTB: 0},
	{Text3: 0},
	{Score: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	roadBlock: class extends self.ISpriteInstance {},
	Ttext1: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	LText1: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	retry: class extends self.IButtonInstance {},
	Cowerd: class extends self.IButtonInstance {},
	PHTB: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {}
}