const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{RedButton: 0},
	{Mouse: 0},
	{Points: 0},
	{OrangeButton: 0},
	{OrangeUnlock: 0},
	{YellowButton: 0},
	{GreenButton: 0},
	{GameName: 0},
	{GameObjective: 0},
	{PlayObjective: 0},
	{PlayButton: 0},
	{BlueButton: 0},
	{PurpleButton: 0},
	{CompleteText1: 0},
	{CompleteText2: 0},
	{RainbowButton: 0},
	{CyanButton: 0},
	{PlayAgainButton: 0},
	{YellowUnlock: 0},
	{GreenUnlock: 0},
	{BlueUnlock: 0},
	{PurpleUnlock: 0},
	{CyanUnlock: 0},
	{RainbowUnlock: 0},
	{GameAudio: 0}
];

self.InstanceType = {
	RedButton: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Points: class extends self.ITextInstance {},
	OrangeButton: class extends self.ISpriteInstance {},
	OrangeUnlock: class extends self.ITextInstance {},
	YellowButton: class extends self.ISpriteInstance {},
	GreenButton: class extends self.ISpriteInstance {},
	GameName: class extends self.ITextInstance {},
	GameObjective: class extends self.ITextInstance {},
	PlayObjective: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	BlueButton: class extends self.ISpriteInstance {},
	PurpleButton: class extends self.ISpriteInstance {},
	CompleteText1: class extends self.ITextInstance {},
	CompleteText2: class extends self.ITextInstance {},
	RainbowButton: class extends self.ISpriteInstance {},
	CyanButton: class extends self.ISpriteInstance {},
	PlayAgainButton: class extends self.ISpriteInstance {},
	YellowUnlock: class extends self.ITextInstance {},
	GreenUnlock: class extends self.ITextInstance {},
	BlueUnlock: class extends self.ITextInstance {},
	PurpleUnlock: class extends self.ITextInstance {},
	CyanUnlock: class extends self.ITextInstance {},
	RainbowUnlock: class extends self.ITextInstance {},
	GameAudio: class extends self.IInstance {}
}