'use strict';function y(g,a,b,d){g.s.tc(g.$a,a,b,d,void 0)}function E(g,a,b,d){g.s.ca?y(g,a,b,d):g.s.wf()._OnMessageFromDOM({type:"event",component:g.$a,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(g,a,b){g.s.C(g.$a,a,b)}function L(g,a){for(const [b,d]of a)J(g,b,d)}function M(g){g.Tb||(g.s.ef(g.me),g.Tb=!0)}window.yb=class{constructor(g,a){this.s=g;this.$a=a;this.Tb=!1;this.me=()=>this.Ca()}ld(){}Ca(){}};function N(g){-1!==g.Pa&&(self.clearTimeout(g.Pa),g.Pa=-1)}
window.Ve=class{constructor(g,a){this.Rc=g;this.Og=a;this.Pa=-1;this.Ub=-Infinity;this.ne=()=>{this.Pa=-1;this.Ub=Date.now();this.fb=!0;this.Rc();this.fb=!1};this.Td=this.fb=!1}f(){N(this);this.ne=this.Rc=null}};"use strict";
function O(g,a){const b=a.elementId,d=g.pd(b,a);g.Y.set(b,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");a=g.Dc(d);a.addEventListener("focus",()=>{P(g,"elem-focused",b)});a.addEventListener("blur",()=>{P(g,"elem-blurred",b)});g.Ob&&document.body.appendChild(d)}function Q(g,a){J(g,"get-element",b=>{const d=g.Y.get(b.elementId);return a(d,b)})}function P(g,a,b){var d;d||(d={});d.elementId=b;y(g,a,d)}
window.Ge=class extends self.yb{constructor(g,a){super(g,a);this.Y=new Map;this.Ob=!0;L(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Ob&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Ob&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ob){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.zc(d,b)}}],["focus",b=>{{const d=this.Dc(this.Y.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,b=>b)}pd(){throw Error("required override");}zc(){throw Error("required override");}Dc(g){return g}};
"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Zg?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.dh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let f=!1,n=!1;function q(){if(!f){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}f=!0}return n}let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=await w(m);return(new TextDecoder("utf-8")).decode(m)}
function w(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Va=class m{constructor(c){this.ca=c.fh;this.qa=null;this.G="";this.hc=c.bh;
this.vb={};this.Ia=this.ub=null;this.Rb=[];this.D=this.Na=null;this.Zd=!1;this.ib=null;this.Ma=-1;this.Tg=()=>this.Xf();this.La=[];this.v=c.oe;this.gb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Xb=this.ia=
null;"html5"!==this.v&&"playable-ad"!==this.v||!this.gb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.Ff(k));
this.C("runtime","create-job-worker",()=>this.Gf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Fd(c)):this.Fd(c)}f(){this.Ac();this.qa&&(this.qa=this.qa.onmessage=null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.f(),this.Ia=null);this.D&&(this.D.parentElement.removeChild(this.D),this.D=null)}Qe(){return g&&"cordova"===this.v}sc(){const c=navigator.userAgent;return g&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Oe(){return a}td(){return a&&
e.has(this.v)}async Fd(c){"macos-wkwebview"===this.v&&this.pg();if("playable-ad"===this.v){this.ia=self.c3_base64files;this.Xb={};await this.kf();for(let l=0,p=c.Qa.length;l<p;++l){var k=c.Qa[l].toLowerCase();this.Xb.hasOwnProperty(k)?c.Qa[l]={Zg:!0,dh:this.Xb[k]}:this.ia.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ia[k]))}}c.Ug?this.G=c.Ug:(k=location.origin,this.G=("null"===k?"file:///":k)+location.pathname,k=this.G.lastIndexOf("/"),-1!==k&&(this.G=this.G.substr(0,k+1)));c.hh&&(this.vb=
c.hh);k=new MessageChannel;this.qa=k.port1;this.qa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Tf(l));this.ib=new self.Re(this);await R(this.ib);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.zf(c,k.port2):await this.yf(c,k.port2)}Ec(c){c=this.vb.hasOwnProperty(c)?this.vb[c]:c.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?
this.vb["workermain.js"]:"playable-ad"===this.v&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async mc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.gb)return c=await this.xb(l.Yg?c:this.hc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}oa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}Dd(c){var k=this.ib;return{baseUrl:this.G,previewUrl:location.href,windowInnerWidth:this.oa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Ta(),projectData:c.nh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.lh||"",exportType:c.oe,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.mh,jobScheduler:{inputPort:k.Yc,outputPort:k.dd,maxNumWorkers:k.Qg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.hc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.hc+"opus.wasm.wasm",isFileProtocol:this.gb,isiOSCordova:this.Qe(),isiOSWebView:this.sc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async zf(c,k){var l=this.Ec(c.gh);this.ub=
await this.mc(l,this.G,{type:"module",name:"Runtime",Yg:!0});this.D=document.createElement("canvas");this.D.style.display="none";l=this.D.transferControlToOffscreen();document.body.appendChild(this.D);window.c3canvas=this.D;let p=c.kd||[],u=c.Qa;p=await Promise.all(p.map(r=>this.Da(r)));u=await Promise.all(u.map(r=>this.Da(r)));if("cordova"===this.v)for(let r=0,t=c.kc.length;r<t;++r){const z=c.kc[r],H=z[0];if(H===c.hd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Da(H)}this.ub.postMessage(Object.assign(this.Dd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.kc,mainProjectScript:c.hd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...S(this.ib)]);this.Rb=F.map(r=>new r(this));this.Cd();self.c3_callFunction=(r,t)=>this.Na.Af(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.tc("runtime","go-to-last-error-script"))}async yf(c,k){this.D=document.createElement("canvas");this.D.style.display="none";document.body.appendChild(this.D);
window.c3canvas=this.D;this.Rb=F.map(r=>new r(this));this.Cd();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.G)).toString():r);Array.isArray(c.kd)&&l.unshift(...c.kd);l=await Promise.all(l.map(r=>this.Da(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.hd,u=c.kc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Da(t),await d(t),"preview"!==this.v||l[r]||this.Nd(r,"main script did not run to completion")}catch(z){this.Nd(r,z)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Da(t),await d(t);"preview"===this.v&&"object"!==typeof self.ih.jh?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Dd(c),{isInWorker:!1,messagePort:k,canvas:this.D,runOnStartupFunctions:K}),this.Hd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,
c))}Nd(c,k){this.Kb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Hd(){this.Kb()}Kb(){const c=window.Vg;c&&(c.parentElement.removeChild(c),window.Vg=null)}async Gf(){const c=await T(this.ib);return{outputPort:c,transferables:[c]}}wf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}tc(c,k,l,p,u){this.qa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}vd(c,k,l,p,u){const r=I++,t=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Lf(c);if("result"===k)this.$f(c);else if("runtime-ready"===k)this.ag();else if("alert-error"===k)this.Kb(),alert(c.message);else if("creating-runtime"===k)this.Hd();else throw Error(`unknown message '${k}'`);
}Lf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Jb(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Jb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Jb(u,!1,""+t)}):this.Jb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.qa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}$f(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static wb(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Cd(){for(const c of this.Rb)if("runtime"===c.$a){this.Na=c;return}throw Error("cannot find runtime DOM handler");
}Tf(c){this.tc("debugger","message",c)}ag(){for(const c of this.Rb)c.ld()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Od(c){h=!!c}ef(c){this.La.push(c);this.Pc()}mg(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.Ac()}Pc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Tg))}Ac(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Xf(){this.Ma=
-1;for(const c of this.La)c();this.Pc()}va(c){this.Na.va(c)}Ba(c){this.Na.Ba(c)}Oc(){this.Na.Oc()}Eb(c){this.Na.Eb(c)}Pe(){return!!B["audio/webm; codecs=opus"]}async Mg(c){c=await this.vd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ye(){this.Zd=!0}Ne(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}ud(c){return!this.Ne(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.gb&&this.ud(c))?(c.startsWith(this.G)&&
(c=c.substr(this.G.length)),c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Ff(c){const k=c.filename;switch(c.as){case "text":return await this.Fe(k);case "buffer":return await this.xb(k);default:throw Error("unsupported type");}}od(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Fe(c){c=await this.od(c);return await D(c)}Bc(){if(x.length&&
!(8<=C)){C++;var c=x.shift();this.lf(c.filename,c.eh,c.Xg)}}xb(c){return new Promise((k,l)=>{x.push({filename:c,eh:p=>{C--;this.Bc();k(p)},Xg:p=>{C--;this.Bc();l(p)}});this.Bc()})}async lf(c,k,l){try{const p=await this.od(c),u=await w(p);k(u)}catch(p){l(p)}}pg(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");
}async kf(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.jf(k,l));await Promise.all(c)}async jf(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Xb[c]=k.str;else{let l=await this.uf(k);l||(l=this.nf(k));this.ia[c]=l}}async uf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}nf(c){c=this.gg(c);return this.hf(c.data,c.$g)}gg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{$g:c,data:l}}hf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const g=self.Va;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function w(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await w(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.wb(class extends self.yb{constructor(e){super(e,"runtime");this.$d=!0;this.Oa=-1;this.fd="any";this.Pd=this.Qd=!1;this.xa=
null;this.Vd="";this.Uc=-1;this.Ha=this.qb=null;this.cc=this.bc=0;this.de=e.oa();this.Vb=e.fa();this.sb=0;e.C("canvas","update-size",c=>this.dg(c));e.C("runtime","invoke-download",c=>this.Rf(c));e.C("runtime","raster-svg-image",c=>this.Yf(c));e.C("runtime","get-svg-image-size",c=>this.Pf(c));e.C("runtime","set-target-orientation",c=>this.bg(c));e.C("runtime","register-sw",()=>this.Zf());e.C("runtime","post-to-debugger",c=>this.Jd(c));e.C("runtime","go-to-script",c=>this.Jd(c));e.C("runtime","before-start-ticking",
()=>this.Ef());e.C("runtime","debug-highlight",c=>this.Hf(c));e.C("runtime","enable-device-orientation",()=>this.gf());e.C("runtime","enable-device-motion",()=>this.ff());e.C("runtime","add-stylesheet",c=>this.Cf(c));e.C("runtime","alert",c=>this.Df(c));e.C("runtime","hide-cordova-splash",()=>this.Qf());e.C("runtime","set-exporting-to-video",c=>this.tg(c));e.C("runtime","export-to-video-progress",c=>this.Mf(c));e.C("runtime","exported-to-video",c=>this.Nf(c));const h=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const m=e.D;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.nb=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.eg());window.addEventListener("fullscreenchange",()=>this.Wa());window.addEventListener("webkitfullscreenchange",()=>this.Wa());window.addEventListener("mozfullscreenchange",()=>this.Wa());window.addEventListener("fullscreenerror",c=>this.Kc(c));window.addEventListener("webkitfullscreenerror",
c=>this.Kc(c));window.addEventListener("mozfullscreenerror",c=>this.Kc(c));if(e.sc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||
"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.fg(c);this.Ja=new Set;this.Yb=new WeakSet;this.pa=!1}Ef(){"cordova"===this.s.v?(document.addEventListener("pause",()=>this.Nc(!0)),document.addEventListener("resume",()=>this.Nc(!1))):document.addEventListener("visibilitychange",()=>this.Nc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}ld(){window.addEventListener("focus",()=>this.Ya("window-focus"));window.addEventListener("blur",()=>
{this.Ya("window-blur",{parentHasFocus:K()});this.nb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||x(h))&&this.Ya("keyboard-blur")});window.addEventListener("keydown",h=>this.Id("keydown",h));window.addEventListener("keyup",h=>this.Id("keyup",h));window.addEventListener("dblclick",h=>this.Lc("dblclick",h,d));window.addEventListener("wheel",h=>this.Vf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.Fc(h);this.Xa("pointerdown",
h)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.qb=new self.Ve(()=>this.rf(),5),this.qb.Td=!0,window.addEventListener("pointerrawupdate",h=>this.Wf(h))):window.addEventListener("pointermove",h=>this.Xa("pointermove",h)),window.addEventListener("pointerup",h=>this.Xa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Xa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Fc(h);this.Mc("pointerdown",h)}),window.addEventListener("mousemove",
h=>this.Mc("pointermove",h)),window.addEventListener("mouseup",h=>this.Mc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Fc(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const e=()=>this.Oc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",
e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.s.Oe()&&!this.s.td()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Ic(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Ic(e,h){document.body.style.transform="";if(0<h){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=
`translateY(${-e}px)`))}}Ya(e,h){y(this,e,h||null,n)}oa(){return this.s.oa()}fa(){return this.s.fa()}eg(){const e=this.oa(),h=this.fa();if(this.s.td()){if(this.de===e&&h<this.Vb){this.sb=this.Vb-h;this.Ic(this.Vb,this.sb);return}0<this.sb&&(this.sb=0,this.Ic(h,this.sb));this.de=e;this.Vb=h}this.Ya("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ta()});this.s.sc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Kd(e,h,0))}ng(e,h,m){-1!==this.Oa&&clearTimeout(this.Oa);
this.Oa=setTimeout(()=>this.Kd(e,h,m),48)}Kd(e,h,m){const c=this.oa(),k=this.fa();this.Oa=-1;c!=e||k!=h?this.Ya("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ta()}):10>m&&this.ng(c,k,m+1)}bg(e){this.fd=e.targetOrientation}Ig(){const e=this.fd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):
screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Wa(){const e=g.Ta();e&&"any"!==this.fd&&this.Ig();y(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.oa(),innerHeight:this.fa()})}Kc(e){console.warn("[Construct 3] Fullscreen request failed: ",
e);y(this,"fullscreenerror",{isFullscreen:g.Ta(),innerWidth:this.oa(),innerHeight:this.fa()})}Nc(e){e?this.s.Ac():this.s.Pc();y(this,"visibilitychange",{hidden:e})}Id(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Vf(e){y(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,
deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Lc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},m)}Mc(e,h){if(!a(h)){var m=this.nb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,
pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.nb=h.buttons;this.Lc(h.type,h,f)}}Xa(e,h){if(this.qb&&"pointermove"!==e){var m=this.qb;m.fb||(N(m),m.Ub=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.nb);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,
movementX:(h.movementX||0)+this.bc,movementY:(h.movementY||0)+this.cc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);this.cc=this.bc=0;"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Lc(m,h,f),this.nb=h.buttons)}Wf(e){this.Ha&&(this.bc+=this.Ha.movementX||0,this.cc+=this.Ha.movementY||0);this.Ha=e;e=this.qb;
if(-1===e.Pa){var h=Date.now(),m=h-e.Ub,c=e.Og;m>=c&&e.Td?(e.Ub=h,e.fb=!0,e.Rc(),e.fb=!1):e.Pa=self.setTimeout(e.ne,Math.max(c-m,4))}}rf(){this.Xa("pointermove",this.Ha);this.Ha=null}Ib(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||
0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}Fc(e){window!==window.top&&window.focus();this.Gd(e.target)&&document.activeElement&&!this.Gd(document.activeElement)&&document.activeElement.blur()}Gd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}gf(){this.Qd||(this.Qd=!0,window.addEventListener("deviceorientation",e=>this.Jf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.Kf(e)))}ff(){this.Pd||(this.Pd=!0,window.addEventListener("devicemotion",e=>this.If(e)))}Jf(e){y(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Kf(e){y(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}If(e){let h=null;var m=e.acceleration;m&&(h=
{x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});y(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}dg(e){var h=this.s;h.Zd||(h=h.D,h.style.width=e.styleWidth+"px",h.style.height=e.styleHeight+"px",h.style.marginLeft=e.marginLeft+"px",h.style.marginTop=e.marginTop+"px",this.$d&&
(h.style.display="",this.$d=!1))}Rf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async Yf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Pf(e){return await self.C3_GetSvgImageSize(e.blob)}async Cf(e){await q(e.url)}Oc(){var e=
[...this.Ja];this.Ja.clear();if(!this.pa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Yb.has(h)||this.Ja.add(h)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Yb.delete(e);let h;try{h=e.play()}catch(m){this.Ja.add(e);return}h&&h.catch(()=>{this.Yb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);this.Yb.add(e)}Eb(e){this.pa=!!e}Qf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Hf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),
this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Zf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Jd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Af(e,h){return this.s.vd(this.$a,"js-invoke-function",{name:e,params:h},void 0,void 0)}Df(e){alert(e.message)}fg(e){"entered-fullscreen"===
e?(g.Od(!0),this.Wa()):"exited-fullscreen"===e?(g.Od(!1),this.Wa()):console.warn("Unknown wrapper message: ",e)}tg(e){const h=document.createElement("h1");h.id="exportToVideoMessage";h.textContent=e.message;document.body.prepend(h);document.body.classList.add("exportingToVideo");this.s.D.style.display="";this.s.Ye()}Mf(e){this.Vd=e.message;-1===this.Uc&&(this.Uc=setTimeout(()=>this.sf(),250))}sf(){this.Uc=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.Vd)}Nf(e){window.kh({type:"exported-video",
blob:e.blob,time:e.time})}})}"use strict";async function R(g){if(g.Ng)throw Error("already initialised");g.Ng=!0;var a=g.fc.Ec("dispatchworker.js");g.Tc=await g.fc.mc(a,g.G,{name:"DispatchWorker"});a=new MessageChannel;g.Yc=a.port1;g.Tc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.dd=await T(g)}function S(g){return[g.Yc,g.dd]}
async function T(g){const a=g.ae.length;var b=g.fc.Ec("jobworker.js");b=await g.fc.mc(b,g.G,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Tc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.ae.push(b);return f.port1}
self.Re=class{constructor(g){this.fc=g;this.G=g.G;this.G="preview"===g.v?this.G+"workers/":this.G+g.hc;this.Qg=Math.min(navigator.hardwareConcurrency||2,16);this.Tc=null;this.ae=[];this.dd=this.Yc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Va({fh:!0,gh:"workermain.js",Qa:["scripts/c3runtime.js"],kc:[],hd:"",bh:"scripts/",kd:[],oe:"html5"}));"use strict";
self.Va.wb(class extends self.yb{constructor(g){super(g,"mouse");L(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.s.D.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{y(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{y(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";
{function g(a){a.stopPropagation()}self.Va.wb(class extends self.Ge{constructor(a){super(a,"button")}pd(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("touchstart",g);
f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>{var n={isChecked:d.checked};n.elementId=a;E(this,"click",n)});b.id&&(d.id=b.id);this.zc(f,b);return f}Ed(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Dc(a){return this.Ed(a)}zc(a,b){const d=this.Ed(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;
a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.da=class extends self.yb{constructor(a){super(a,"audio");this.Qb=this.c=null;this.Sb=this.Xc=!1;this.sa=()=>this.Jg();this.aa=[];this.F=[];this.ha=null;this.be="";this.ce=-1;this.pb=new Map;this.ad=1;this.pa=!1;this.gd=0;this.ic=1;this.Vc=0;this.fe="HRTF";this.Ud="inverse";this.ge=600;this.ee=1E4;this.ie=1;this.Xd=this.ed=!1;this.le=this.s.Pe();this.ba=new Map;this.Fa=new Set;this.Zc=!1;this.bd="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Uf(b,d);this.Pb=null;
self.C3Audio_GetOutputStream=()=>this.Of();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.mf(b)],["play",b=>this.hg(b)],["stop",b=>this.Gg(b)],["stop-all",()=>this.Hg()],["set-paused",b=>this.zg(b)],["set-volume",b=>this.Eg(b)],["fade-volume",b=>this.tf(b)],["set-master-volume",b=>this.xg(b)],["set-muted",b=>this.yg(b)],["set-silent",b=>this.Bg(b)],["set-looping",b=>this.wg(b)],["set-playback-rate",b=>this.Ag(b)],["seek",b=>this.og(b)],["preload",b=>this.ig(b)],["unload",b=>
this.Kg(b)],["unload-all",()=>this.Lg()],["set-suspended",b=>this.Cg(b)],["get-suspended",()=>this.xf()],["add-effect",b=>this.Ad(b)],["set-effect-param",b=>this.sg(b)],["remove-effects",b=>this.kg(b)],["tick",b=>this.cg(b)],["load-state",b=>this.Sf(b)]])}async mf(a){a.isiOSCordova&&(this.ed=!0);this.gd=a.timeScaleMode;this.fe=["equalpower","HRTF","soundfield"][a.panningModel];this.Ud=["linear","inverse","exponential"][a.distanceModel];this.ge=a.refDistance;this.ee=a.maxDistance;this.ie=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.le||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Bd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Bd()};this.Qb=this.c.createGain();this.Qb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.nc();try{await Promise.all(a.preloadList.map(d=>this.Gb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}Bd(){this.Sb||(this.Xc=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Sb=!0)}pf(){this.Sb&&(this.Xc=!0,window.removeEventListener("pointerup",this.sa,!0),
window.removeEventListener("touchend",this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Sb=!1)}Jg(){if(!this.Xc){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.pf()}}W(){return this.c}nc(){return this.c.currentTime}ta(){return this.Qb}rd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ta()}pe(a,
b){a=a.toLowerCase();let d=this.ba.get(a);d||(d=[],this.ba.set(a,d));b.vg(d.length);b.Dg(a);d.push(b);this.Md(a)}Md(a){let b=this.ta();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let f=0,n=d.length;f<n;++f){const q=d[f];f+1===n?q.S(this.ta()):q.S(d[f+1].P())}}for(const f of this.ma(a))f.We(b);this.ya&&this.bd===a&&(this.ya.disconnect(),this.ya.connect(b))}Ab(){return this.ad}Bb(){return this.pa}ug(){this.Xd=!0}Ie(a,b){return b?this.s.Mg(a).then(d=>{const f=this.c.createBuffer(1,d.length,
48E3);f.getChannelData(0).set(d);return f}):new Promise((d,f)=>{this.c.decodeAudioData(a,d,f)})}va(a){this.s.va(a)}Ba(a){this.s.Ba(a)}wd(a){let b=0;for(let d=0,f=this.F.length;d<f;++d){const n=this.F[d];this.F[b]=n;n.L===a?n.f():++b}this.F.length=b}Xe(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const f=this.aa[b];this.aa[a]=f;f.ua()?f.f():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.F)self.da.Je(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Gb(a,b,d,f,n){for(const q of this.aa)if(q.Sa()===
b)return await U(q),q;if(n)return null;f&&(this.ed||this.Xd)&&this.Xe();n="audio/webm; codecs=opus"===d&&!this.le;f&&n&&this.ug();a=!f||this.ed||n?new self.De(this,a,b,d,f,n):new self.Be(this,a,b,d,f);this.aa.push(a);await U(a);return a}async Cc(a,b,d,f,n){for(const q of this.F)if(q.Sa()===b&&(q.lc()||n))return q.$e(f),q;a=await this.Gb(a,b,d,n);f="html5"===a.Qc?new self.Ce(a.i,a,f):new self.Ee(a.i,a,f);this.F.push(f);return f}df(a){let b=this.pb.get(a);if(!b){let d=null;b={jd:0,ah:new Promise(f=>
d=f),resolve:d};this.pb.set(a,b)}b.jd++}lg(a){const b=this.pb.get(a);if(!b)throw Error("expected pending tag");b.jd--;0===b.jd&&(b.resolve(),this.pb.delete(a))}yc(a){a||(a=this.be);return(a=this.pb.get(a))?a.ah:Promise.resolve()}Hb(){if(0<this.Fa.size)M(this);else for(const a of this.F)if(a.sd()){M(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.nc();for(var b of this.F)b.Ca(a);b=this.F.filter(d=>d.sd()).map(d=>d.Ra());y(this,"state",{tickCount:this.ce,audioInstances:b,analysers:[...this.Fa].map(d=>
d.Le())});0===b.length&&0===this.Fa.size&&this.Tb&&(this.s.mg(this.me),this.Tb=!1)}uc(a,b,d){y(this,"trigger",{type:a,tag:b,aiid:d})}async hg(a){const b=a.originalUrl,d=a.url,f=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.c.currentTime);this.be=q;this.df(q);try{this.ha=await this.Cc(b,d,f,q,n),w?(this.ha.Db(!0),this.ha.Ze(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ha.af(w.uid)):this.ha.Db(!1),this.ha.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.lg(q)}M(this)}Gg(a){a=a.tag;for(const b of this.ma(a))b.na()}Hg(){for(const a of this.F)a.na()}zg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Ua():d.Cb();this.Hb()}Eg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Fb(a)}async tf(a){const b=a.tag,d=a.vol,
f=a.duration;a=a.stopOnEnd;await this.yc(b);for(const n of this.ma(b))n.Ke(d,f,a);this.Hb()}xg(a){this.ad=a.vol;for(const b of this.F)b.Mb()}yg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.xd(a)}Bg(a){this.pa=a.isSilent;this.s.Eb(this.pa);for(const b of this.F)b.Lb()}wg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.wc(a)}async Ag(a){const b=a.tag;a=a.rate;await this.yc(b);for(const d of this.ma(b))d.zd(a)}async og(a){const b=a.tag;a=a.pos;await this.yc(b);for(const d of this.ma(b))d.vc(a)}async ig(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.Cc(b,d,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Kg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}Lg(){for(const a of this.aa)a.f();this.aa.length=0}Cg(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.F)b.xc(a);a&&this.c.suspend&&this.c.suspend()}xf(){return this.c?this.c.state:"suspended"}cg(a){this.ic=a.timeScale;
this.Vc=a.gameTime;this.ce=a.tickCount;if(0!==this.gd)for(var b of this.F)b.Ea();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.F)f.ga===a&&f.yd(d.x,d.y,d.angle)}}async Ad(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.ve(this,...f);else if("delay"===b)f=new self.te(this,...f);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}f=new self.se(this,b.$,...f);f.qg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.we(this,...f);else if("phaser"===b)f=new self.ye(this,...f);else if("gain"===b)f=new self.xe(this,...f);else if("tremolo"===b)f=new self.Ae(this,...f);else if("ringmod"===b)f=new self.ze(this,...f);else if("distortion"===b)f=new self.ue(this,...f);else if("compressor"===b)f=new self.re(this,...f);else if("analyser"===b)f=new self.qe(this,...f);else throw Error("invalid effect type");this.pe(d,
f);this.Ld()}sg(a){const b=a.index,d=a.param,f=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,n,q),this.Ld())}kg(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.f();this.ba.delete(a);this.Md(a)}}cf(a){this.Fa.add(a);this.Hb()}jg(a){this.Fa.delete(a)}Ld(){this.Zc||(this.Zc=!0,Promise.resolve().then(()=>this.qf()))}qf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(f=>f.Ra());y(this,"fxstate",{fxstate:a});this.Zc=!1}async Sf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.F)d.ua()&&1===b||(d.ua()||2!==b)&&d.na();for(const f of this.ba.values())for(const n of f)n.f();this.ba.clear();this.ic=a.timeScale;this.Vc=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.pa=a.isSilent;this.s.Eb(this.pa);this.ad=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(n=>this.Ad(n))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.Bf(f,b)));this.Hb()}async Bf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Cc(d,f,n,v,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Ue(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Ua();b.Hc(a)}}}Uf(a,b){this.ya&&this.ya.disconnect();this.bd=b.toLowerCase();this.ya=this.c.createMediaStreamSource(a);this.ya.connect(this.rd(this.bd))}Of(){this.Pb||(this.Pb=this.c.createMediaStreamDestination(),
this.Qb.connect(this.Pb));return this.Pb.stream}static Je(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static bf(a){return a*g}static He(a){return Math.pow(10,a/20)}static qd(a){return Math.max(Math.min(self.da.He(a),1),0)}static Te(a){return Math.log(a)/Math.log(10)*20}static Se(a){return self.da.Te(Math.max(Math.min(a,1),0))}static Wg(a,b){return 1-Math.exp(-b*a)}};self.Va.wb(self.da)}"use strict";function U(g){g.Wb||(g.Wb=g.Gc());return g.Wb}
self.md=class{constructor(g,a,b,d,f){this.i=g;this.Sg=a;this.za=b;this.R=d;this.Pg=f;this.Qc="";this.Wb=null}f(){this.Wb=this.i=null}Gc(){}W(){return this.i.W()}pc(){return this.Sg}Sa(){return this.za}oc(){return this.R}ua(){return this.Pg}ea(){}};"use strict";
self.Be=class extends self.md{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Qc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.jb=this.kb=null;this.K.addEventListener("canplaythrough",()=>!0);this.ob=this.W().createGain();this.mb=null;this.K.addEventListener("canplay",()=>{this.kb&&(this.kb(),this.jb=this.kb=null);!this.mb&&this.K&&(this.mb=this.W().createMediaElementSource(this.K),this.mb.connect(this.ob))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.jb&&(this.jb(n),this.jb=this.kb=null)})}f(){this.i.wd(this);this.ob.disconnect();this.ob=null;this.mb.disconnect();this.mb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Gc(){return new Promise((g,a)=>{this.kb=g;this.jb=a;this.K.src=this.za})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function V(g){if(g.wa)return g.wa;var a=g.i.s;if("cordova"===a.v&&a.ud(g.za)&&a.gb)g.wa=await a.xb(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function W(g){if(g.$)return g.$;g.$=await g.i.Ie(g.wa,g.Rg);g.wa=null}
self.De=class extends self.md{constructor(g,a,b,d,f,n){super(g,a,b,d,f);this.Qc="webaudio";this.$=this.wa=null;this.Rg=!!n}f(){this.i.wd(this);this.$=this.wa=null;super.f()}async Gc(){try{await V(this),await W(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let g=0;self.nd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Nb=g++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.hb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.tb=1;this.Ga=!1;this.ra=1;a=this.i.gd;this.$c=1===a&&!this.ua()||2===a;this.cb=this.ga=-1;this.ke=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.rd(this.Z)}Ab(){return this.i.Ab()}zb(){return this.$c?
this.i.Vc:performance.now()/1E3}pc(){return this.L.pc()}Sa(){return this.L.Sa()}oc(){return this.L.oc()}ua(){return this.L.ua()}$e(a){this.Z=a}T(){}lc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}sd(){return!this.I&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}na(){}Ua(){}Cb(){}Fb(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.cb=-1;this.M.gain.value=this.qc()}Ke(a,b,d){if(!this.Ga){a*=this.Ab();var f=this.M.gain;f.cancelScheduledValues(0);var n=this.i.nc();b=n+b;f.setValueAtTime(f.value,
n);f.linearRampToValueAtTime(a,b);this.tb=a;this.cb=b;this.ke=d}}Mb(){this.Fb(this.tb)}Ca(a){-1!==this.cb&&a>=this.cb&&(this.cb=-1,this.ke&&this.na(),this.i.uc("fade-ended",this.Z,this.Nb))}qc(){const a=this.tb*this.Ab();return isFinite(a)?a:0}xd(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Lb())}Bb(){return this.i.Bb()}Lb(){}wc(){}zd(a){this.ra!==a&&(this.ra=a,this.Ea())}Ea(){}vc(){}xc(){}Db(a){a=!!a;this.hb!==a&&((this.hb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.fe,this.B.distanceModel=
this.i.Ud,this.B.refDistance=this.i.ge,this.B.maxDistance=this.i.ee,this.B.rolloffFactor=this.i.ie),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}Ze(a,b,d,f,n,q){this.hb&&(this.yd(a,b,d),a=self.da.bf,this.B.coneInnerAngle=a(f),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}yd(a,b,d){this.hb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}af(a){this.ga=a}rc(){}We(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Nb,tag:this.Z,duration:this.ea(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.ra,uid:this.ga,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.rc(),pan:this.Me()}}Hc(a){this.zd(a.playbackRate);this.xd(a.isMuted)}Me(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ue(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Db(!1)}}}"use strict";
self.Ce=class extends self.nd{constructor(g,a,b){super(g,a,b);this.L.ob.connect(this.M);this.L.onended=()=>this.Jc()}f(){this.na();this.L.ob.disconnect();super.f()}O(){return this.L.O()}Jc(){this.I=!0;this.ga=-1;this.i.uc("ended",this.Z,this.Nb)}T(){return this.O().ended}lc(){return this.I?!0:this.T()}Aa(){let g=this.O().currentTime;this.V||(g=Math.min(g,this.ea()));return g}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,f)}this.i.va(d);this.H=this.I=!1;this.V=g;this.ra=1}na(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.I=!0;this.H=!1;this.ga=-1}Ua(){if(!(this.H||this.I||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0}}Cb(){!this.H||this.I||this.T()||(this.i.va(this.O()),this.H=!1)}Lb(){this.O().muted=this.Ga||this.Bb()}wc(g){g=!!g;this.V!==g&&
(this.V=g,this.O().loop=g)}Ea(){let g=this.ra;this.$c&&(g*=this.i.ic);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}vc(g){if(!this.I&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}rc(){return this.Aa()}xc(g){g?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function X(g){g.j&&g.j.disconnect();g.j=null;g.Za=null}
self.Ee=class extends self.nd{constructor(g,a,b){super(g,a,b);this.j=null;this.Zb=d=>this.Jc(d);this.Wc=!0;this.Za=null;this.N=this.$b=this.ac=0;this.cd=1}f(){this.na();X(this);this.Zb=null;super.f()}Jc(g){this.H||this.la||g.target!==this.Za||(this.I=this.Wc=!0,this.ga=-1,X(this),this.i.uc("ended",this.Z,this.Nb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Wc}lc(){return!this.j||this.I?!0:this.T()}Aa(){let g;g=this.H?this.N:this.$b+(this.zb()-this.ac)*this.ra;this.V||(g=Math.min(g,this.ea()));
return g}Play(g,a,b,d){this.cd=1;this.Fb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Zb;this.j.loop=g;this.j.start(d,b);this.H=this.I=this.Wc=!1;this.V=g;this.ra=1;this.ac=this.zb();this.$b=b}na(){if(this.j)try{this.j.stop(0)}catch(g){}this.I=!0;this.H=!1;this.ga=-1}Ua(){this.H||this.I||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Cb(){!this.H||this.I||this.T()||(X(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.V,this.Mb(),this.Ea(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.H=!1)}qc(){return super.qc()*this.cd}Lb(){this.cd=this.Ga||this.Bb()?0:1;this.Mb()}wc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Ea(){let g=this.ra;this.$c&&(g*=this.i.ic);this.j&&(this.j.playbackRate.value=g)}vc(g){this.I||this.T()||(this.H?this.N=g:(this.Ua(),this.N=g,this.Cb()))}rc(){return this.N}xc(g){g?
this.IsPlaying()?(this.la=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.V,this.Mb(),this.Ea(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.la=!1)}Hc(g){super.Hc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.c=a.W();this.Yd=-1;this.R=this.Z="";this.g=null}f(){this.c=null}vg(a){this.Yd=a}Dg(a){this.Z=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.c.currentTime;f+=n;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.Z,params:this.g}}}
self.ve=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="filter";this.g=[b,d,f,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=f;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,f)}}};self.te=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.lb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.bb=this.o();this.bb.gain.value=d;this.l.connect(this.lb);this.l.connect(this.a);this.lb.connect(this.b);this.lb.connect(this.U);this.U.connect(this.bb);this.bb.connect(this.lb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.lb.disconnect();this.U.disconnect();this.bb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const n=self.da.qd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=n(b);this.m(this.bb.gain,n(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.se=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Sd=this.Rd="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.ab=this.c.createConvolver();this.ab.normalize=d;this.ab.buffer=b;this.l.connect(this.ab);this.l.connect(this.a);this.ab.connect(this.b)}f(){this.l.disconnect();this.ab.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}qg(a,b){this.Rd=a;this.Sd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Rd;a.bufferUrl="";a.bufferType=this.Sd;return a}};self.we=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="flanger";this.g=[b,d,f,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.eb=this.o();this.eb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.u=this.c.createOscillator();this.u.frequency.value=f;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.eb);this.eb.connect(this.U);this.u.connect(this.J);this.J.connect(this.U.delayTime);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.eb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.eb.gain,b/100,d,f)}}};self.ye=class extends g{constructor(a,b,d,f,n,q,v){super(a);this.R="phaser";this.g=[b,d,f,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=f;this.u=this.c.createOscillator();this.u.frequency.value=q;this.J=this.o();this.J.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.u.connect(this.J);this.J.connect(this.A.frequency);this.u.start(0)}f(){this.u.stop(0);this.l.disconnect();this.A.disconnect();this.u.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,f)}}};self.xe=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const n=self.da.qd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,f)}}};self.Ae=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.c.createOscillator();this.u.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.u.connect(this.J);this.J.connect(this.h.gain);this.u.start(0)}f(){this.u.stop(0);this.u.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.J.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,f)}}};self.ze=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.rb=this.o();this.rb.gain.value=
0;this.u=this.c.createOscillator();this.u.frequency.value=b;this.u.connect(this.rb.gain);this.u.start(0);this.l.connect(this.rb);this.l.connect(this.a);this.rb.connect(this.b)}f(){this.u.stop(0);this.u.disconnect();this.rb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,f)}}};self.ue=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="distortion";this.g=[b,d,f,n,q];this.l=this.o();this.ec=this.o();this.dc=this.o();this.rg(f,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.jc=this.c.createWaveShaper();this.Sc=new Float32Array(65536);this.vf(b,d);this.jc.curve=this.Sc;this.l.connect(this.ec);this.l.connect(this.a);this.ec.connect(this.jc);this.jc.connect(this.dc);
this.dc.connect(this.b)}f(){this.l.disconnect();this.ec.disconnect();this.jc.disconnect();this.dc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}rg(a,b){.01>a&&(a=.01);this.ec.gain.value=a;this.dc.gain.value=Math.pow(1/a,.6)*b}vf(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.Fg(f,a,b);this.Sc[32768+d]=f;this.Sc[32768-d-1]=-f}}Fg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.da.Wg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.re=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="compressor";this.g=[b,d,f,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.qe=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Wd=new Float32Array(this.h.frequencyBinCount);this.je=new Uint8Array(b);this.he=this.Ka=0;this.i.cf(this)}f(){this.i.jg(this);this.h.disconnect();super.f()}Ca(){this.h.getFloatFrequencyData(this.Wd);this.h.getByteTimeDomainData(this.je);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let f=(this.je[d]-128)/128;0>f&&(f=-f);
this.Ka<f&&(this.Ka=f);b+=f*f}d=self.da.Se;this.Ka=d(this.Ka);this.he=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Le(){return{tag:this.Z,index:this.Yd,peak:this.Ka,rms:this.he,binCount:this.h.frequencyBinCount,freqBins:this.Wd}}}};
